/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.FoodDonation.FoodDonationDirectory;
import Business.FoodDonor.FoodDonorDirectory;
import Business.FoodPantry.FoodPantryDirectory;
import Business.FoodPantry.FoodPantryItemsDirectory;
import Business.FoodWarehouse.FoodWarehouseDirectory;
import Business.NonGovtOrg.NonGovtOrgDirectory;
import Business.NonGovtOrgVolunteer.NGOVolunteerRequestsDirectory;
import Business.NonGovtOrgVolunteer.NGOVolunteerDirectory;

import Business.Organization;
import Business.FoodRequestorder.FoodRequestorderDirectory;
import Business.FoodRequestor.FoodRequestorDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import userinterface.DonorRole.DonorAreaJPanel;
import userinterface.FCAdminRole.FCAdminWorkAreaPanel;
import userinterface.FCPManagerRole.FCPManagerWorkAreaPanel;
import userinterface.NGORole.ManageVolunteerPanel;
import userinterface.NGORole.NGOWorkAreaPanel;
import userinterface.RequestorRole.RequestorAreaJPanel;
import userinterface.RestaurantAdminRole.AdminWorkAreaJPanel;
import userinterface.Signup.SignupWorkAreaJPanel;
import userinterface.SystemAdminWorkArea.AddWarehousePanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import userinterface.VolunteerRole.VolunteerWorkAreaPanel;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount ua;
    FoodRequestorDirectory rd;
    FoodDonorDirectory dd;
    FoodWarehouseDirectory fcd;

    public MainJFrame() throws IOException {
        initComponents();

        this.setSize(1680, 1050);
        ecosystem = dB4OUtil.retrieveSystem();
        if (ecosystem == null) {
            ecosystem = new EcoSystem(new FoodRequestorDirectory(), new FoodDonorDirectory(), new FoodWarehouseDirectory(), new NonGovtOrgDirectory(), new NGOVolunteerDirectory(),
                                        new FoodPantryDirectory(),new FoodPantryItemsDirectory(), new FoodDonationDirectory(), new FoodRequestorderDirectory() 
                                        , new NGOVolunteerRequestsDirectory());
        }

        Image img = ImageIO.read(getClass().getResource("/Images/background.jpg"));
        Image newimg = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), java.awt.Image.SCALE_SMOOTH);
        jLabel3.setIcon(new ImageIcon(newimg));

        Image icon = ImageIO.read(getClass().getResource("/Images/logo.png"));
        Image newIcon = icon.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(newIcon));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordtxtField = new javax.swing.JPasswordField();
        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(0, 153, 204));

        loginJButton.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel.setText("Username");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel1.setText("Password");

        logoutJButton.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        btnNewUser.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnNewUser.setText("Register");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(loginJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel)
                                .addGap(50, 50, 50)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginJLabel)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutJButton)
                        .addGap(27, 27, 27)
                        .addComponent(btnNewUser)))
                .addContainerGap(544, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel);

        container.setPreferredSize(new java.awt.Dimension(1100, 900));
        container.setLayout(new java.awt.CardLayout());

        jLabel3.setPreferredSize(new java.awt.Dimension(333, 400));
        container.add(jLabel3, "card2");

        jSplitPane.setRightComponent(container);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name

        String username = userNameJTextField.getText();
        String password = passwordtxtField.getText();
        UserAccountDirectory userDirectory = ecosystem.getUserAccountDirectory();

        this.ua = userDirectory.authenticateUser(username, password);
        if (ua == null) {
            JOptionPane.showMessageDialog(this, "Invalid credentials!!");
        } else {

            jSplitPane.setOneTouchExpandable(true);
            jSplitPane.setDividerLocation(0.0);

            if (ua.getRole().toString().equals("Business.Role.SystemAdminRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                SystemAdminWorkAreaJPanel sa = new SystemAdminWorkAreaJPanel(container, ecosystem, jPanel, jSplitPane);
                container.add("Sysadmin", sa);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            } else if (ua.getRole().toString().equals("Business.Role.FCAdminRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                FCAdminWorkAreaPanel fca = new FCAdminWorkAreaPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("FCAdmin", fca);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            } else if (ua.getRole().toString().equals("Business.Role.DonorRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                DonorAreaJPanel don = new DonorAreaJPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("Donor", don);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            } else if (ua.getRole().toString().equals("Business.Role.RequestorRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                RequestorAreaJPanel req = new RequestorAreaJPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("Requestor", req);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            }
            else if (ua.getRole().toString().equals("Business.Role.NgoRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                NGOWorkAreaPanel req = new NGOWorkAreaPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("NGOAgent", req);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            }
            else if (ua.getRole().toString().equals("Business.Role.FCPManagerRole")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                FCPManagerWorkAreaPanel fcpm = new FCPManagerWorkAreaPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("FCPManager", fcpm);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            }
            else if (ua.getRole().toString().equals("Business.Role.DeliveryVolunteer")) {

                userNameJTextField.setEnabled(false);
                passwordtxtField.setEnabled(false);
                loginJButton.setEnabled(false);
                logoutJButton.setEnabled(true);

                VolunteerWorkAreaPanel vol = new VolunteerWorkAreaPanel(container, ecosystem, ua, jPanel, jSplitPane);
                container.add("Volunteer", vol);
                CardLayout crdLyt = (CardLayout) container.getLayout();
                crdLyt.next(container);
            }
        }


    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logout(container, jPanel, jSplitPane);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        try {
            // TODO add your handling code here:
            SignupWorkAreaJPanel sp = new SignupWorkAreaJPanel(container, ecosystem);

            container.add("NewUser", sp);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container, "NewUser");

        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewUserActionPerformed

    public void logout(JPanel container, JPanel jp, JSplitPane jsp) {
        try {

            Component[] component = jp.getComponents();

            for (int i = 0; i < component.length; i++) {
                if (component[i] instanceof JTextField) {
                    JTextField jt = (JTextField) component[i];
                    jt.setEnabled(true);
                    jt.setText("");
                }

                if (component[i] instanceof JButton) {
                    JButton jb = (JButton) component[i];
                    if (jb.getText() == "Login") {
                        jb.setEnabled(true);
                    }
                    if (jb.getText() == "Logout") {
                        jb.setEnabled(false);
                    }

                }

            }
            
            jsp.setOneTouchExpandable(true);
            jsp.setDividerLocation(0.2);

            container.removeAll();
            HomeJPanel hmJP = new HomeJPanel(container);
            container.add("Home", hmJP);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
            dB4OUtil.storeSystem(ecosystem);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        AddWarehousePanel panel = new AddWarehousePanel(
                new ImageIcon("images/blurbg.png").getImage());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewUser;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordtxtField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
