/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Worker.Worker;
import Business.FoodPantry.FoodPantry;
import Business.FoodPantry.FoodPantryDirectory;
import Business.FoodWarehouse.FoodWarehouse;
import Business.Role.FCPManagerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorProfilePanel;

/**
 *
 * @author admin
 */
public class AddFCPantryPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFCPantryPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    FoodPantryDirectory fcpd;
    UserAccountDirectory uad;

    public AddFCPantryPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if (ecosystem.getFCPDirectory() == null) {
            ecosystem.setFCPDirectory(new FoodPantryDirectory());
        }
        ArrayList<String> whList = new ArrayList<String>();
        for (FoodWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()) {
            whList.add(fcw.getFcwName());
        }
        cbWarehouse.setModel(new DefaultComboBoxModel<String>(whList.toArray(new String[0])));
        setBG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddPantryTitle = new javax.swing.JLabel();
        lblPantryname = new javax.swing.JLabel();
        txtPantryname = new javax.swing.JTextField();
        lblPantryPhone = new javax.swing.JLabel();
        txtPantryPhone = new javax.swing.JTextField();
        lblPantryAdd = new javax.swing.JLabel();
        txtPantryAdd = new javax.swing.JTextField();
        lblPantryCity = new javax.swing.JLabel();
        txtPantryCity = new javax.swing.JTextField();
        lblPantryState = new javax.swing.JLabel();
        txtPantryState = new javax.swing.JTextField();
        lblPantryZip = new javax.swing.JLabel();
        txtPantryZip = new javax.swing.JTextField();
        lblPantryManager = new javax.swing.JLabel();
        txtPantryManager = new javax.swing.JTextField();
        lblPantryuname = new javax.swing.JLabel();
        txtPantryuname = new javax.swing.JTextField();
        lblPantrypwd = new javax.swing.JLabel();
        txtPantrypwd = new javax.swing.JTextField();
        lblPantrypwd1 = new javax.swing.JLabel();
        txtPantrypwd1 = new javax.swing.JTextField();
        btnPantrySubmit = new javax.swing.JButton();
        lblWHPantryname = new javax.swing.JLabel();
        lblPantryid = new javax.swing.JLabel();
        txtPantryid = new javax.swing.JTextField();
        lblWHPantryname1 = new javax.swing.JLabel();
        lblPantryid1 = new javax.swing.JLabel();
        lblPantryname1 = new javax.swing.JLabel();
        lblPantryPhone1 = new javax.swing.JLabel();
        lblPantryAdd1 = new javax.swing.JLabel();
        lblPantryCity1 = new javax.swing.JLabel();
        lblPantryState1 = new javax.swing.JLabel();
        lblPantryZip1 = new javax.swing.JLabel();
        lblPantryManager1 = new javax.swing.JLabel();
        lblPantryuname1 = new javax.swing.JLabel();
        lblPantrypwd2 = new javax.swing.JLabel();
        lblPantrypwd3 = new javax.swing.JLabel();
        cbWarehouse = new javax.swing.JComboBox<>();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddPantryTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddPantryTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblAddPantryTitle.setText("Add Pantry");
        add(lblAddPantryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        lblPantryname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryname.setText("Pantry Name:");
        add(lblPantryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        txtPantryname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantrynameFocusLost(evt);
            }
        });
        add(txtPantryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 136, 137, -1));

        lblPantryPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryPhone.setText("Phone Number:");
        add(lblPantryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        txtPantryPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantryPhoneFocusLost(evt);
            }
        });
        add(txtPantryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 179, 137, -1));

        lblPantryAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryAdd.setText("Address:");
        add(lblPantryAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        txtPantryAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtPantryAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 222, 137, -1));

        lblPantryCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryCity.setText("City:");
        add(lblPantryCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        txtPantryCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtPantryCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 265, 137, -1));

        lblPantryState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryState.setText("State:");
        add(lblPantryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        txtPantryState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryState.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantryStateActionPerformed(evt);
            }
        });
        add(txtPantryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 308, 137, -1));

        lblPantryZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryZip.setText("Zip:");
        add(lblPantryZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        txtPantryZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantryZipFocusLost(evt);
            }
        });
        txtPantryZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantryZipActionPerformed(evt);
            }
        });
        add(txtPantryZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 351, 137, -1));

        lblPantryManager.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryManager.setText("Pantry Manager Name:");
        add(lblPantryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        txtPantryManager.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryManager.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantryManagerFocusLost(evt);
            }
        });
        add(txtPantryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 394, 137, -1));

        lblPantryuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryuname.setText("Pantry Manager Username:");
        add(lblPantryuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        txtPantryuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryuname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantryunameFocusLost(evt);
            }
        });
        add(txtPantryuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 437, 137, -1));

        lblPantrypwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantrypwd.setText("Password:");
        add(lblPantrypwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        txtPantrypwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantrypwd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantrypwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantrypwdActionPerformed(evt);
            }
        });
        add(txtPantrypwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 480, 137, -1));

        lblPantrypwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantrypwd1.setText("Confirm Password:");
        add(lblPantrypwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        txtPantrypwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantrypwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantrypwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantrypwd1FocusLost(evt);
            }
        });
        add(txtPantrypwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 523, 137, -1));

        btnPantrySubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnPantrySubmit.setText("Submit");
        btnPantrySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantrySubmitActionPerformed(evt);
            }
        });
        add(btnPantrySubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        lblWHPantryname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWHPantryname.setText("Warehouse Name:");
        add(lblWHPantryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lblPantryid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPantryid.setText("Pantry ID:");
        add(lblPantryid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        txtPantryid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtPantryid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPantryid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPantryidFocusLost(evt);
            }
        });
        add(txtPantryid, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 94, 137, -1));

        lblWHPantryname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblWHPantryname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 53, -1, -1));

        lblPantryid1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 94, -1, -1));

        lblPantryname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 136, -1, -1));

        lblPantryPhone1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 179, -1, -1));

        lblPantryAdd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 222, -1, -1));

        lblPantryCity1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 265, -1, -1));

        lblPantryState1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 308, -1, -1));

        lblPantryZip1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 351, -1, -1));

        lblPantryManager1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryManager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 394, -1, -1));

        lblPantryuname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryuname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 437, -1, -1));

        lblPantrypwd2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantrypwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 480, -1, -1));

        lblPantrypwd3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantrypwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 523, -1, -1));

        cbWarehouse.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbWarehouse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 700));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtPantrynameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantrynameFocusLost
        // TODO add your handling code here:
        if (!(txtPantryname.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryname1.setText("");
        }
    }//GEN-LAST:event_txtPantrynameFocusLost

    private void txtPantryPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantryPhoneFocusLost
        // TODO add your handling code here:
        if (!(txtPantryPhone.getText().matches("^[0-9]*$")) || !(txtPantryPhone.getText().length() == 10)) {
            lblPantryPhone1.setText("Please enter a valid phone number");
        } else {
            lblPantryPhone1.setText("");

        }
    }//GEN-LAST:event_txtPantryPhoneFocusLost

    private void txtPantryZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantryZipFocusLost
        // TODO add your handling code here:
        if ((txtPantryZip.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryZip1.setText("Invalid input. Please enter only numbers");
        } else {
            lblPantryZip1.setText("");
        }
    }//GEN-LAST:event_txtPantryZipFocusLost

    private void txtPantryManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantryManagerFocusLost
        // TODO add your handling code here:
        if (!(txtPantryManager.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryManager1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryManager1.setText("");
        }
    }//GEN-LAST:event_txtPantryManagerFocusLost

    public boolean isValid(String test, String regex) {
//        String regex = "^[A-Za-z0-9]+";
        Pattern p = Pattern.compile(regex);

        if (test == null) {
            return false;
        }

        Matcher m = p.matcher(test);

        return m.matches();
    }


    private void btnPantrySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantrySubmitActionPerformed
        // TODO add your handling code here:

        if (!nullCheck()) {
            if (chkpwd()) {

                String panid = txtPantryid.getText();
                String panName = txtPantryname.getText();
                String phone = txtPantryPhone.getText();

                String panCity = txtPantryCity.getText();
                String panState = txtPantryState.getText();
                String panZip = txtPantryZip.getText();
                String panManager = txtPantryManager.getText();
                String panUser = txtPantryuname.getText();
                String panPswd = txtPantrypwd.getText();
                if (!isValid(panid, "^[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid ID");
                    return;
                }
                if (!isValid(panName, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid name");
                    return;
                }
                if (!isValid(phone, "[+]?[0-9]{10,13}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid phone number");
                    return;
                }
                if (!isValid(panCity, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid city");
                    return;
                }
                if (!isValid(panState, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){2,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid state");
                    return;
                }
                if (!isValid(panZip, "^[0-9]{5}(?:-[0-9]{4})?$")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid zip");
                    return;
                }
                if (!isValid(panManager, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid name");
                    return;
                }
                if (!isValid(panUser, "^[a-zA-Z0-9._-]{6,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid username of atleast 6 characters");
                    return;
                }
                if (!isValid(panPswd, "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password of atleast 8 characters in length. It must contain a number, a specicial character, a lowercase and an uppercase character.");
                    return;
                }

                UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
                Worker employee = new Worker();
                employee.setName(txtPantryManager.getText());
                String role = "FCPManager";
                FoodPantry fcp = new FoodPantry();
                fcp.setFcpId("fcp" + txtPantryid.getText());
                fcp.setFcpWHname(cbWarehouse.getSelectedItem().toString());
                fcp.setFcpName(txtPantryname.getText());
                fcp.setFcpPhno(txtPantryPhone.getText());
                fcp.setFcpAddres(txtPantryAdd.getText());
                fcp.setFcpCity(txtPantryCity.getText());
                fcp.setFcpState(txtPantryState.getText());
                fcp.setFcpZipcode(txtPantryZip.getText());
                fcp.setFcpManager(txtPantryManager.getText());
                UserAccount fcPantryAccount = new UserAccount();
                fcPantryAccount.setUsername(txtPantryuname.getText());
                fcPantryAccount.setPassword(txtPantrypwd.getText());
                fcPantryAccount.setRole(new FCPManagerRole());
                fcPantryAccount.setEmployee(employee);
                uad = ecosystem.getUserAccountDirectory();
                uad.createUserAccount(txtPantryuname.getText(), txtPantrypwd.getText(), employee, new FCPManagerRole());
                ecosystem.setUserAccountDirectory(uad);
                fcp.setFcpAccount(fcPantryAccount);
                System.out.println(fcp);
                System.out.println("here");
                fcpd = ecosystem.getFCPDirectory();
                fcpd.addNewFCPantry(fcp);
                System.out.println(fcpd);
                System.out.println(ecosystem.getFCPDirectory().getFcpList());

                ecosystem.setFCPDirectory(fcpd);
                Integer pantryCnt = ecosystem.getPantryCnt();
                ecosystem.setPantryCnt(pantryCnt + 1);

                JOptionPane.showMessageDialog(this, "Food Cloud Pantry added successfully!");
                clearfields();
                //  fcPantryAccount.setRole(new FCAdminRole());
                //fcp.setFcpAccount(fcPantryAccount);
                // ecosystem.getFCPDirectory().addNewFCPantry(fcp);
            } else {
                JOptionPane.showMessageDialog(this, "Password Mismatch. Please verify the password entered.");
                txtPantrypwd1.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnPantrySubmitActionPerformed

    private void txtPantryStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantryStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantryStateActionPerformed

    private void txtPantryZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantryZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantryZipActionPerformed

    private void txtPantryidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantryidFocusLost
        // TODO add your handling code here:
        if ((txtPantryid.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryid1.setText("Invalid input. Please enter only numbers");
        } else {
            lblPantryid1.setText("");
        }
    }//GEN-LAST:event_txtPantryidFocusLost

    private void txtPantryunameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantryunameFocusLost
        // TODO add your handling code here:
        if (!(txtPantryuname.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryuname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryuname1.setText("");
        }
    }//GEN-LAST:event_txtPantryunameFocusLost


    private void txtPantrypwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPantrypwd1FocusLost
        // TODO add your handling code here:
//        if(!(txtFCPpwd.getText().equals(txtFCPpwd1.getText()))){
//            lblFCApwd2.setText("Password Mismatch. Please verify the password entered.");
//        }
//        else{
//            lblFCApwd2.setText("");
//        }
    }//GEN-LAST:event_txtPantrypwd1FocusLost

    private void txtPantrypwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantrypwdActionPerformed

        if (!Business.Validations.ValidateInputs.isPasswordValid(txtPantrypwd.getText())) {
            JOptionPane.showMessageDialog(this, "Please verify the password (min 8).");
        }
    }//GEN-LAST:event_txtPantrypwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnPantrySubmit;
    private javax.swing.JComboBox<String> cbWarehouse;
    private javax.swing.JLabel lblAddPantryTitle;
    private javax.swing.JLabel lblPantryAdd;
    private javax.swing.JLabel lblPantryAdd1;
    private javax.swing.JLabel lblPantryCity;
    private javax.swing.JLabel lblPantryCity1;
    private javax.swing.JLabel lblPantryManager;
    private javax.swing.JLabel lblPantryManager1;
    private javax.swing.JLabel lblPantryPhone;
    private javax.swing.JLabel lblPantryPhone1;
    private javax.swing.JLabel lblPantryState;
    private javax.swing.JLabel lblPantryState1;
    private javax.swing.JLabel lblPantryZip;
    private javax.swing.JLabel lblPantryZip1;
    private javax.swing.JLabel lblPantryid;
    private javax.swing.JLabel lblPantryid1;
    private javax.swing.JLabel lblPantryname;
    private javax.swing.JLabel lblPantryname1;
    private javax.swing.JLabel lblPantrypwd;
    private javax.swing.JLabel lblPantrypwd1;
    private javax.swing.JLabel lblPantrypwd2;
    private javax.swing.JLabel lblPantrypwd3;
    private javax.swing.JLabel lblPantryuname;
    private javax.swing.JLabel lblPantryuname1;
    private javax.swing.JLabel lblWHPantryname;
    private javax.swing.JLabel lblWHPantryname1;
    private javax.swing.JTextField txtPantryAdd;
    private javax.swing.JTextField txtPantryCity;
    private javax.swing.JTextField txtPantryManager;
    private javax.swing.JTextField txtPantryPhone;
    private javax.swing.JTextField txtPantryState;
    private javax.swing.JTextField txtPantryZip;
    private javax.swing.JTextField txtPantryid;
    private javax.swing.JTextField txtPantryname;
    private javax.swing.JTextField txtPantrypwd;
    private javax.swing.JTextField txtPantrypwd1;
    private javax.swing.JTextField txtPantryuname;
    // End of variables declaration//GEN-END:variables

    private boolean nullCheck() {
        if (txtPantryid.getText().length() != 0 && txtPantryname.getText().length() != 0
                && txtPantryPhone.getText().length() != 0 && txtPantryAdd.getText().length() != 0 && txtPantryCity.getText().length() != 0
                && txtPantryState.getText().length() != 0 && txtPantryZip.getText().length() != 0 && txtPantryManager.getText().length() != 0
                && txtPantryuname.getText().length() != 0 && txtPantrypwd.getText().length() != 0 && txtPantrypwd1.getText().length() != 0) {
            return false;
        } else {
            return true;
        }
    }

    private void clearfields() {
        txtPantryid.setText("");
        txtPantryname.setText("");
        cbWarehouse.setSelectedIndex(0);
        txtPantryPhone.setText("");
        txtPantryAdd.setText("");
        txtPantryCity.setText("");
        txtPantryState.setText("");
        txtPantryZip.setText("");
        txtPantryManager.setText("");
        txtPantryuname.setText("");
        txtPantrypwd.setText("");
        txtPantrypwd1.setText("");
    }

    private boolean chkpwd() {
        if (txtPantrypwd.getText().equals(txtPantrypwd1.getText())) {
            return true;
        } else {
            return false;
        }
    }
}
