/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import userinterface.DonorRole.DonorProfilePanel;

/**
 *
 * @author admin
 */
public class ManageUsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUsers
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory uad;

    public ManageUsersPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        setBG();
        setLogo();
        populateUserTable();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewUsersTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblViewUsers = new javax.swing.JTable();
        btnUsersDelete = new javax.swing.JButton();
        logoImg = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(2000, 1100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewUsersTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblViewUsersTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblViewUsersTitle.setText("View Users");
        add(lblViewUsersTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 24, -1, -1));

        tblViewUsers.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblViewUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Role", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewUsersMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblViewUsersMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblViewUsers);
        if (tblViewUsers.getColumnModel().getColumnCount() > 0) {
            tblViewUsers.getColumnModel().getColumn(0).setResizable(false);
            tblViewUsers.getColumnModel().getColumn(1).setResizable(false);
            tblViewUsers.getColumnModel().getColumn(2).setResizable(false);
            tblViewUsers.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 865, 212));

        btnUsersDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnUsersDelete.setText("Delete");
        btnUsersDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersDeleteActionPerformed(evt);
            }
        });
        add(btnUsersDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 92, -1));
        add(logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, 80));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1500, 720));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(1500, 1000));
            LabelImg.setPreferredSize(new Dimension(1500, 1000));
            LabelImg.setMaximumSize(new Dimension(1500, 1000));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(2500, 1000, java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setLogo() {
        try {
            logoImg.setMinimumSize(new Dimension(100, 100));
            logoImg.setPreferredSize(new Dimension(100, 100));
            logoImg.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void makeTableTransparent() {
        tblViewUsers.setOpaque(false);
        ((DefaultTableCellRenderer) tblViewUsers.getDefaultRenderer(Object.class)).setOpaque(false);
        tblViewUsers.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

       
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);
   //     headerRenderer.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 30));
        for (int i = 0; i < tblViewUsers.getModel().getColumnCount(); i++) {
            tblViewUsers.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        
    }

    private void btnUsersDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblViewUsers.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblViewUsers.getModel();
        UserAccount selectedUA = (UserAccount) model.getValueAt(selectedRowIndex, 0);
        if(selectedUA.getRole().toString().equals("Business.Role.SystemAdminRole")){
            JOptionPane.showMessageDialog(this, "You cannot delete System Admin login!");
        }
        else if(selectedUA.getRole().toString().equals("Business.Role.FCAdminRole") ){
            JOptionPane.showMessageDialog(this, "You cannot delete this login!"
                    + "You can only delete the warehouse or update the admin name");
        }
        else if(selectedUA.getRole().toString().equals("Business.Role.FCPManagerRole")){
             JOptionPane.showMessageDialog(this, "You cannot delete this login!"
                    + "You can only delete the pantry or update the manager name");
        }
        else if(selectedUA.getRole().toString().equals("Business.Role.NgoRole")){
            JOptionPane.showMessageDialog(this, "You cannot delete this login!"
                    + "You can only delete the ngo or update the agent name");
        }
        else{
        uad = ecosystem.getUserAccountDirectory();
        uad.deleteUserAccount(selectedUA);
        ecosystem.setUserAccountDirectory(uad);
        JOptionPane.showMessageDialog(this, "User Account deleted Successfully");
        }
        populateUserTable();
    }//GEN-LAST:event_btnUsersDeleteActionPerformed

    private void tblViewUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewUsersMousePressed
        // TODO add your handling code here:
        //tblUsers.setSelectionBackground(Color.BLUE );
        tblViewUsers.setSelectionForeground(Color.BLUE);

    }//GEN-LAST:event_tblViewUsersMousePressed

    private void tblViewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewUsersMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblViewUsersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnUsersDelete;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblViewUsersTitle;
    private javax.swing.JLabel logoImg;
    private javax.swing.JTable tblViewUsers;
    // End of variables declaration//GEN-END:variables

    private void populateUserTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewUsers.getModel();
        model.setRowCount(0);
        for (UserAccount ua : ecosystem.getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[4];
            row[0] = ua;
            row[1] = ua.getPassword();
            row[2] = getRoles(ua.getRole().toString());
            row[3] = ua.getEmployee();
            model.addRow(row);
        }
    }

    private Object getRoles(String role) {
        String rl = "";
        
        if(role.equals("Business.Role.SystemAdminRole")){
             rl="System Admin";
        }else if(role.equals("Business.Role.FCAdminRole")){
            rl="FC Admin";
        }else if(role.equals("Business.Role.FCPManagerRole")){
            rl="FCP Manager";
        }else if(role.equals("Business.Role.NgoRole")){
            rl="NGO";
        }else if(role.equals("Business.Role.DonorRole")){
            rl="Donor";
        }else if(role.equals("Business.Role.RequestorRole")){
            rl="Requestor";
        }else if(role.equals("Business.Role.DeliveryVolunteer")){
            rl="Volunteer";
        }
        
        return rl;
    }

}
