/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ManageNGOJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNGOJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    public ManageNGOJPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer = userProcessContainer;
        lblNGObgc.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblNGObgc.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblNGObgc.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

        Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
        lblNGObgc.setIcon(new ImageIcon(newimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneNonGovtOrg = new javax.swing.JSplitPane();
        NonGovtOrgControlPanel = new javax.swing.JPanel();
        btnNGOAddNGO = new javax.swing.JButton();
        btnNGOView = new javax.swing.JButton();
        SysAdminNGOWorkareaPanel = new javax.swing.JPanel();
        lblNGObgc = new javax.swing.JLabel();

        NonGovtOrgControlPanel.setBackground(new java.awt.Color(255, 255, 255));
        NonGovtOrgControlPanel.setPreferredSize(new java.awt.Dimension(150, 600));

        btnNGOAddNGO.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnNGOAddNGO.setText("Add NGO");
        btnNGOAddNGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOAddNGOActionPerformed(evt);
            }
        });

        btnNGOView.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnNGOView.setText("View/Modify");
        btnNGOView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NonGovtOrgControlPanelLayout = new javax.swing.GroupLayout(NonGovtOrgControlPanel);
        NonGovtOrgControlPanel.setLayout(NonGovtOrgControlPanelLayout);
        NonGovtOrgControlPanelLayout.setHorizontalGroup(
            NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NonGovtOrgControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNGOView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNGOAddNGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NonGovtOrgControlPanelLayout.setVerticalGroup(
            NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NonGovtOrgControlPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnNGOAddNGO)
                .addGap(26, 26, 26)
                .addComponent(btnNGOView)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        SplitPaneNonGovtOrg.setLeftComponent(NonGovtOrgControlPanel);

        SysAdminNGOWorkareaPanel.setPreferredSize(new java.awt.Dimension(840, 600));

        javax.swing.GroupLayout SysAdminNGOWorkareaPanelLayout = new javax.swing.GroupLayout(SysAdminNGOWorkareaPanel);
        SysAdminNGOWorkareaPanel.setLayout(SysAdminNGOWorkareaPanelLayout);
        SysAdminNGOWorkareaPanelLayout.setHorizontalGroup(
            SysAdminNGOWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNGObgc, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        SysAdminNGOWorkareaPanelLayout.setVerticalGroup(
            SysAdminNGOWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNGObgc, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        SplitPaneNonGovtOrg.setRightComponent(SysAdminNGOWorkareaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNonGovtOrg, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNonGovtOrg)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNGOAddNGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOAddNGOActionPerformed
        try {
            // TODO add your handling code here:
            AddNGOPanel objAddNGO = new AddNGOPanel(userProcessContainer,ecosystem);
            SplitPaneNonGovtOrg.setRightComponent(objAddNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageNGOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNGOAddNGOActionPerformed

    private void btnNGOViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOViewActionPerformed
        try {
            // TODO add your handling code here:
            ViewModifyNGOPanel objViewModNGO = new ViewModifyNGOPanel(userProcessContainer,ecosystem);
            SplitPaneNonGovtOrg.setRightComponent(objViewModNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageNGOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNGOViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NonGovtOrgControlPanel;
    private javax.swing.JSplitPane SplitPaneNonGovtOrg;
    private javax.swing.JPanel SysAdminNGOWorkareaPanel;
    private javax.swing.JButton btnNGOAddNGO;
    private javax.swing.JButton btnNGOView;
    private javax.swing.JLabel lblNGObgc;
    // End of variables declaration//GEN-END:variables
}
