/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;

import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userinterface.DonorRole.DonorAreaJPanel;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.FCAdminRole.FCAdminWorkAreaPanel;
import userinterface.MainJFrame;

/**
 *
 * @author admin
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    JPanel jp;
    JSplitPane jsp;
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.jp = jp;
        this.jsp = jsp;
      //  this.userAcc = userAcc;
      logoutlogo();
      setBG();
      setLogo();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SysAdminSplitPane = new javax.swing.JSplitPane();
        MenubarSysAdminPanel = new javax.swing.JPanel();
        btnManageWarehouse = new javax.swing.JButton();
        btnManagePantry = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        lblSysadminWelcomemsg = new javax.swing.JLabel();
        btnManageNonGovtOrg = new javax.swing.JButton();
        lblsysadminlogout = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        logoImg = new javax.swing.JLabel();
        btnViewAllStats = new javax.swing.JButton();
        WorkAreaSysadminPanel = new javax.swing.JPanel();
        LabelImage = new javax.swing.JLabel();

        SysAdminSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenubarSysAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenubarSysAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageWarehouse.setBackground(new java.awt.Color(0, 153, 204));
        btnManageWarehouse.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManageWarehouse.setText("Manage Warehouse");
        btnManageWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWarehouseActionPerformed(evt);
            }
        });
        MenubarSysAdminPanel.add(btnManageWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        btnManagePantry.setBackground(new java.awt.Color(0, 153, 204));
        btnManagePantry.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManagePantry.setText("Manage Pantry");
        btnManagePantry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePantryActionPerformed(evt);
            }
        });
        MenubarSysAdminPanel.add(btnManagePantry, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        btnManageUsers.setBackground(new java.awt.Color(0, 153, 204));
        btnManageUsers.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });
        MenubarSysAdminPanel.add(btnManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        lblSysadminWelcomemsg.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblSysadminWelcomemsg.setForeground(new java.awt.Color(0, 153, 204));
        lblSysadminWelcomemsg.setText("Welcome System Admin!");
        MenubarSysAdminPanel.add(lblSysadminWelcomemsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        btnManageNonGovtOrg.setBackground(new java.awt.Color(0, 153, 204));
        btnManageNonGovtOrg.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManageNonGovtOrg.setText("Manage NGO");
        btnManageNonGovtOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNonGovtOrgActionPerformed(evt);
            }
        });
        MenubarSysAdminPanel.add(btnManageNonGovtOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        lblsysadminlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsysadminlogoutMousePressed(evt);
            }
        });
        MenubarSysAdminPanel.add(lblsysadminlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 40, 30));
        MenubarSysAdminPanel.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 60, 120));
        MenubarSysAdminPanel.add(logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        btnViewAllStats.setBackground(new java.awt.Color(0, 153, 204));
        btnViewAllStats.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnViewAllStats.setText("View System Stats");
        btnViewAllStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllStatsActionPerformed(evt);
            }
        });
        MenubarSysAdminPanel.add(btnViewAllStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        SysAdminSplitPane.setLeftComponent(MenubarSysAdminPanel);

        WorkAreaSysadminPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        LabelImage.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N

        javax.swing.GroupLayout WorkAreaSysadminPanelLayout = new javax.swing.GroupLayout(WorkAreaSysadminPanel);
        WorkAreaSysadminPanel.setLayout(WorkAreaSysadminPanelLayout);
        WorkAreaSysadminPanelLayout.setHorizontalGroup(
            WorkAreaSysadminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        WorkAreaSysadminPanelLayout.setVerticalGroup(
            WorkAreaSysadminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        SysAdminSplitPane.setRightComponent(WorkAreaSysadminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SysAdminSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SysAdminSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setLogo() {
        try {
            logoImg.setMinimumSize(new Dimension(100, 100));
            logoImg.setPreferredSize(new Dimension(100, 100));
            logoImg.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/logo.png"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
      public void logoutlogo() {

        try {
           
            lblsysadminlogout.setMinimumSize(new Dimension(50,60));
            lblsysadminlogout.setPreferredSize(new Dimension(50,60));
            lblsysadminlogout.setMaximumSize(new Dimension(50,60));
            
            Image img1 = ImageIO.read(getClass().getResource("/Images/signout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lblsysadminlogout.setIcon(new ImageIcon(newimg1));
            
            
        } catch (IOException ex) {
            Logger.getLogger(DonorAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
      
    private void btnManageWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWarehouseActionPerformed
        // TODO add your handling code here:
        ManageWarehousePanel objWH = new ManageWarehousePanel(userProcessContainer,ecosystem);
        SysAdminSplitPane.setRightComponent(objWH);
        /*userProcessContainer.add("Manage Warehouse",objWH);
        CardLayout crdlyt = (CardLayout) userProcessContainer.getLayout();
        crdlyt.next(userProcessContainer); */
    }//GEN-LAST:event_btnManageWarehouseActionPerformed

    private void btnManagePantryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePantryActionPerformed
        // TODO add your handling code here:
        ManagePantryPanel objFCP = new ManagePantryPanel(userProcessContainer,ecosystem);
         SysAdminSplitPane.setRightComponent(objFCP);
       /* userProcessContainer.add("Manage Pantry",objFCP);
        CardLayout crdlyt = (CardLayout) userProcessContainer.getLayout();
        crdlyt.next(userProcessContainer); */
    }//GEN-LAST:event_btnManagePantryActionPerformed

    private void btnManageNonGovtOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNonGovtOrgActionPerformed
        try {
            // TODO add your handling code here:
            ManageNGOJPanel objNGO = new ManageNGOJPanel(userProcessContainer,ecosystem);
            SysAdminSplitPane.setRightComponent(objNGO);
        } catch (IOException ex) {
            Logger.getLogger(SystemAdminWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManageNonGovtOrgActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
        ManageUsersPanel objUSER = new ManageUsersPanel(userProcessContainer,ecosystem);
         SysAdminSplitPane.setRightComponent(objUSER);
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void lblsysadminlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsysadminlogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblsysadminlogoutMousePressed

    private void btnViewAllStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllStatsActionPerformed
        // TODO add your handling code here:
        ViewAllStatsPanel objSTATS = new ViewAllStatsPanel(userProcessContainer,ecosystem);
         SysAdminSplitPane.setRightComponent(objSTATS);
    }//GEN-LAST:event_btnViewAllStatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JPanel MenubarSysAdminPanel;
    private javax.swing.JSplitPane SysAdminSplitPane;
    private javax.swing.JPanel WorkAreaSysadminPanel;
    private javax.swing.JButton btnManageNonGovtOrg;
    private javax.swing.JButton btnManagePantry;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnManageWarehouse;
    private javax.swing.JButton btnViewAllStats;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel lblSysadminWelcomemsg;
    private javax.swing.JLabel lblsysadminlogout;
    private javax.swing.JLabel logoImg;
    // End of variables declaration//GEN-END:variables
}
