/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.FoodDonation.FoodDonation;
import Business.EcoSystem;
import Business.FoodWarehouse.FoodWarehouse;
import Business.FoodPantry.FoodPantry;
import Business.FoodPantry.FoodPantryItems;
import Business.NonGovtOrgVolunteer.NGOVolunteer;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class DonationRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonations
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String volname;
    String WHname;
    String city;
    public DonationRequestsPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        String FCAname=userAcc.getEmployee().getName();
        System.out.println(FCAname);
        WHname= ecosystem.getFCWDirectory().getWHname(FCAname);
        for(FoodWarehouse f: ecosystem.getFCWDirectory().getFcwList()){
            if(f.getFcwName().equals(WHname)){
                city=f.getFcwCity();
            }
        }
        ArrayList<String> VolunteerList = new ArrayList();
        for (NGOVolunteer vol : ecosystem.getVolDir().getVolunteerList()){
            if(vol.getVolCity().equals(city) && vol.getVolAvail().equals("Yes")){
            VolunteerList.add(vol.getVolName());
            }
        }
        cbVolunteer.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
        
//        String fcpitem = cbSelectPantry.getSelectedItem().toString();
       
        ArrayList<String> fcPantryList = new ArrayList<>();

        for (  FoodPantry e : ecosystem.getFCPDirectory().getFcpList()){
            if(e.getFcpWHname().equals(WHname)){
            fcPantryList.add(e.getFcpName());
            }
        }
        System.out.println(fcPantryList);
        System.out.println("sff");
        cbSelectPantry.setModel(new DefaultComboBoxModel<String>(fcPantryList.toArray(new String[0])));
        
        populateTable();
        setBG();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonRequestsTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblDonReq = new javax.swing.JTable();
        btnReqAssign = new javax.swing.JButton();
        lblDReqid = new javax.swing.JLabel();
        txtDReqid = new javax.swing.JTextField();
        lblDReqid1 = new javax.swing.JLabel();
        cbVolunteer = new javax.swing.JComboBox<>();
        btnReqSend = new javax.swing.JButton();
        lblDonReqTitle1 = new javax.swing.JLabel();
        lblSelectPantry = new javax.swing.JLabel();
        cbSelectPantry = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDonRequestsTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblDonRequestsTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblDonRequestsTitle.setText("Donation Requests");
        add(lblDonRequestsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 14, -1, -1));

        tblDonReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblDonReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Donation ID", "Food Item", "Quantity", "Warehouse", "Status"
            }
        ));
        tblDonReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDonReqMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblDonReq);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1030, 153));

        btnReqAssign.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnReqAssign.setText("Assign");
        btnReqAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqAssignActionPerformed(evt);
            }
        });
        add(btnReqAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        lblDReqid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDReqid.setText("Donation ID :");
        add(lblDReqid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        txtDReqid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDReqid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDReqid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDReqidFocusLost(evt);
            }
        });
        txtDReqid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDReqidKeyReleased(evt);
            }
        });
        add(txtDReqid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 137, -1));

        lblDReqid1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDReqid1.setText("Assign Volunteer :");
        add(lblDReqid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        cbVolunteer.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbVolunteer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVolunteerActionPerformed(evt);
            }
        });
        add(cbVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 140, -1));

        btnReqSend.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnReqSend.setText("Send request to volunteer");
        btnReqSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqSendActionPerformed(evt);
            }
        });
        add(btnReqSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        lblDonReqTitle1.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        lblDonReqTitle1.setForeground(new java.awt.Color(0, 153, 204));
        lblDonReqTitle1.setText("Assign Volunteer");
        add(lblDonReqTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        lblSelectPantry.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblSelectPantry.setText("Select Pantry:");
        add(lblSelectPantry, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        cbSelectPantry.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbSelectPantry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        cbSelectPantry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectPantryActionPerformed(evt);
            }
        });
        add(cbSelectPantry, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtDReqidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDReqidFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtDReqidFocusLost

    private void txtDReqidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDReqidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDReqidKeyReleased

    public void setBG() {
        try {
//            fcpLblSelect.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            fcpLblSelect.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            fcpLblSelect.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1650, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//            fcpLblSelect.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(ViewPantryItemsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  public void makeTableTransparent() {
        tblDonReq.setOpaque(false);
        ((DefaultTableCellRenderer) tblDonReq.getDefaultRenderer(Object.class)).setOpaque(false);
        tblDonReq.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblDonReq.getModel().getColumnCount(); i++) {
            tblDonReq.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void btnReqSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqSendActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblDonReq.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDonReq.getModel();
        FoodDonation selectedD = (FoodDonation)model.getValueAt(selectedRowIndex, 0);
        txtDReqid.setText(selectedD.getDonatId());
    }//GEN-LAST:event_btnReqSendActionPerformed

    private void btnReqAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqAssignActionPerformed
        // TODO add your handling code here:
        String Donid = txtDReqid.getText();
        String fcpitem = cbSelectPantry.getSelectedItem().toString();
        System.out.println(fcpitem +" fcpitem...");
        FoodDonation curD = new FoodDonation();
        for(FoodDonation d: ecosystem.getDonatDirectory().getDonatList()){
            System.out.println(Donid +" .... " + d.getDonatId());
            if(d.getDonatId() == null ? Donid == null : d.getDonatId().equals(Donid)){
            volname= cbVolunteer.getSelectedItem().toString();
            d.setDonatVol(volname);
            curD = d;
            d.setDonatStatus("Assigned to Volunteer");
            System.out.println(volname + " " + Donid +"dsf");
        }
        
        
//            FoodPantryItems fcpi=new FoodPantryItems();
//            fcpi.setFcpitemid(txtitemId.getText());
//            fcpi.setFcpWHname(WHname);
//            fcpi.setPantryName(String.valueOf(cbPantry.getSelectedItem()));
//            fcpi.setPantryManager(txtPM.getText());
//            fcpi.setFoodItem(txtFDitem.getText());
//            fcpi.setFoodQuan(txtFDq.getText());           
//            fcpid = ecosystem.getFCPIDirectory();
//            fcpid.addFCPItems(fcpi);
//            ecosystem.setFCPIDirectory(fcpid);            
            
            
        
        }
        
        
        
        for(FoodPantry fcp: ecosystem.getFCPDirectory().getFcpList()){
            if(fcp.getFcpName().equals(fcpitem)){
            FoodPantryItems fcpi = new FoodPantryItems();
            fcpi.setPantryManager(fcp.getFcpManager());
            fcpi.setFoodQuan(curD.getDonatFoodQuant());
            fcpi.setFcpitemid(curD.getDonatId());
            fcpi.setFoodItem(curD.getDonatFooditem());
            fcpi.setFcpWHname(WHname);
            fcpi.setPantryName(fcpitem);
            System.out.println("pappa andi start");
            System.out.println(fcpi);
            ecosystem.getFCPIDirectory().addFCPItems(fcpi);
            System.out.println("pappa andi");
            System.out.println(ecosystem.getFCPIDirectory().getFcpiList());
             System.out.println("pappa andi end");
            
            }
        }
        for(NGOVolunteer v:ecosystem.getVolDir().getVolunteerList()){
            if(v.getVolName().equals(volname)){
                v.setVolAvail("No");
            }
        }
        JOptionPane.showMessageDialog(this, "Pickup Request Assigned to Volunteer Successfully!");
        populateTable();
    }//GEN-LAST:event_btnReqAssignActionPerformed

    private void tblDonReqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonReqMousePressed
        // TODO add your handling code here:
        tblDonReq.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblDonReqMousePressed

    private void cbSelectPantryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectPantryActionPerformed
        // TODO add your handling code here:
        
//        String fcpitem = cbSelectPantry.getSelectedItem().toString();
//       
//        ArrayList<String> fcPantryList = new ArrayList<>();
//
//        for (  FoodPantry e : ecosystem.getFCPDirectory().getFcpList()){
//            fcPantryList.add(e.getFcpName());
//        }
//        System.out.println(fcPantryList);
//        System.out.println("sff");
//        cbSelectPantry.setModel(new DefaultComboBoxModel<String>(fcPantryList.toArray(new String[0])));
    }//GEN-LAST:event_cbSelectPantryActionPerformed

    private void cbVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVolunteerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVolunteerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReqAssign;
    private javax.swing.JButton btnReqSend;
    private javax.swing.JComboBox<String> cbSelectPantry;
    private javax.swing.JComboBox<String> cbVolunteer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblDReqid;
    private javax.swing.JLabel lblDReqid1;
    private javax.swing.JLabel lblDonReqTitle1;
    private javax.swing.JLabel lblDonRequestsTitle;
    private javax.swing.JLabel lblSelectPantry;
    private javax.swing.JTable tblDonReq;
    private javax.swing.JTextField txtDReqid;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        System.out.println(1);
        DefaultTableModel model = (DefaultTableModel) tblDonReq.getModel();
        model.setRowCount(0);
        System.out.println(ecosystem.getDonatDirectory().getDonatList());
        for(FoodDonation dt: ecosystem.getDonatDirectory().getDonatList()){
            System.out.println(dt.getDonatStatus());
            System.out.println(dt.getDonatWHname().equals(WHname));
            if(dt.getDonatWHname().equals(WHname) && dt.getDonatStatus() != "Delivered"){
           Object[] row = new Object[5];
           row[0] =dt;
           row[1] =dt.getDonatFooditem();
           row[2] =dt.getDonatFoodQuant();
           row[3] =dt.getDonatWHname();
           row[4] =dt.getDonatStatus();
           model.addRow(row);
            }
        } 
    }
}
