/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.MainJFrame;

/**
 *
 * @author admin
 */
public class FCAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form FCAdminWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    JPanel jp;
    JSplitPane jsp;
    public FCAdminWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount userAccount, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.jp = jp;
        this.jsp = jsp;
        setBG();
        logoutlogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneFCAdmin = new javax.swing.JSplitPane();
        FCAMenubarPanel = new javax.swing.JPanel();
        btnViewDonationReq = new javax.swing.JButton();
        btnManagePItems = new javax.swing.JButton();
        btnManageVol = new javax.swing.JButton();
        lblWelcomemessage = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        FCAWorkAreaPanel = new javax.swing.JPanel();
        LabelImage = new javax.swing.JLabel();

        SplitPaneFCAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        FCAMenubarPanel.setBackground(new java.awt.Color(255, 255, 255));
        FCAMenubarPanel.setToolTipText("");

        btnViewDonationReq.setBackground(new java.awt.Color(0, 153, 204));
        btnViewDonationReq.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnViewDonationReq.setText("View Donation Requests");
        btnViewDonationReq.setToolTipText("");
        btnViewDonationReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationReqActionPerformed(evt);
            }
        });

        btnManagePItems.setBackground(new java.awt.Color(0, 153, 204));
        btnManagePItems.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManagePItems.setText("Manage Pantry Items");
        btnManagePItems.setToolTipText("");
        btnManagePItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePItemsActionPerformed(evt);
            }
        });

        btnManageVol.setBackground(new java.awt.Color(0, 153, 204));
        btnManageVol.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnManageVol.setText("Manage Volunteers");
        btnManageVol.setToolTipText("");
        btnManageVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolActionPerformed(evt);
            }
        });

        lblWelcomemessage.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblWelcomemessage.setForeground(new java.awt.Color(51, 153, 255));
        lblWelcomemessage.setText("Welcome, Food Cloud Admin!");

        lbllogout.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllogoutMousePressed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N

        javax.swing.GroupLayout FCAMenubarPanelLayout = new javax.swing.GroupLayout(FCAMenubarPanel);
        FCAMenubarPanel.setLayout(FCAMenubarPanelLayout);
        FCAMenubarPanelLayout.setHorizontalGroup(
            FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FCAMenubarPanelLayout.createSequentialGroup()
                .addGroup(FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FCAMenubarPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnManagePItems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewDonationReq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManageVol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FCAMenubarPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWelcomemessage)
                        .addGap(120, 120, 120)))
                .addComponent(jLabel)
                .addGap(153, 153, 153)
                .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        FCAMenubarPanelLayout.setVerticalGroup(
            FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FCAMenubarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FCAMenubarPanelLayout.createSequentialGroup()
                        .addComponent(lblWelcomemessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FCAMenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnManagePItems)
                                .addComponent(btnManageVol)
                                .addComponent(btnViewDonationReq))
                            .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(FCAMenubarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        SplitPaneFCAdmin.setLeftComponent(FCAMenubarPanel);

        FCAWorkAreaPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        LabelImage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FCAWorkAreaPanelLayout = new javax.swing.GroupLayout(FCAWorkAreaPanel);
        FCAWorkAreaPanel.setLayout(FCAWorkAreaPanelLayout);
        FCAWorkAreaPanelLayout.setHorizontalGroup(
            FCAWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        FCAWorkAreaPanelLayout.setVerticalGroup(
            FCAWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FCAWorkAreaPanelLayout.createSequentialGroup()
                .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SplitPaneFCAdmin.setRightComponent(FCAWorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFCAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFCAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonationReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationReqActionPerformed
        // TODO add your handling code here:
        DonationRequestsPanel objDonReq =  new DonationRequestsPanel(userProcessContainer,ecosystem,userAccount);
        SplitPaneFCAdmin.setRightComponent(objDonReq);
    }//GEN-LAST:event_btnViewDonationReqActionPerformed

    private void btnManagePItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePItemsActionPerformed
        // TODO add your handling code here:
        ManagePantryItemsPanel objWHI = new ManagePantryItemsPanel(userProcessContainer,ecosystem,userAccount);
        SplitPaneFCAdmin.setRightComponent(objWHI);
    }//GEN-LAST:event_btnManagePItemsActionPerformed

    private void btnManageVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolActionPerformed
        // TODO add your handling code here:
        ManageVolunteerPanel objVol =  new ManageVolunteerPanel(userProcessContainer,ecosystem,userAccount);
        SplitPaneFCAdmin.setRightComponent(objVol);
    }//GEN-LAST:event_btnManageVolActionPerformed

    private void lbllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbllogoutMousePressed

    public void logoutlogo() {

        try {
           
            lbllogout.setMinimumSize(new Dimension(50,60));
            lbllogout.setPreferredSize(new Dimension(50,60));
            lbllogout.setMaximumSize(new Dimension(50,60));
            
            Image img1 = ImageIO.read(getClass().getResource("/Images/signout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lbllogout.setIcon(new ImageIcon(newimg1));
            
            
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
  public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FCAMenubarPanel;
    private javax.swing.JPanel FCAWorkAreaPanel;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JSplitPane SplitPaneFCAdmin;
    private javax.swing.JButton btnManagePItems;
    private javax.swing.JButton btnManageVol;
    private javax.swing.JButton btnViewDonationReq;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel lblWelcomemessage;
    private javax.swing.JLabel lbllogout;
    // End of variables declaration//GEN-END:variables
}
