/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.EcoSystem;
import Business.FoodPantry.FoodPantryItems;
import Business.FoodPantry.FoodPantryItemsDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewPantryItemsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPantryItemsPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    FoodPantryItemsDirectory fcpid;
    String FCPname;
    String WHname;

    public ViewPantryItemsPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        
        //FCPname = ecosystem.getFCPDirectory();
        String FCAname = userAcc.getEmployee().getName();
        System.out.println(FCAname);
        WHname= ecosystem.getFCWDirectory().getWHname(FCAname);
         System.out.println(WHname + "satish Whname");
        viewPanel.setVisible(false);
        setBG();
        populatePantryItemsTable();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddPantryTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblPItems = new javax.swing.JTable();
        btnPEdit = new javax.swing.JButton();
        btnPDelete = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();
        txtFoodItem = new javax.swing.JTextField();
        txtFCPManager = new javax.swing.JTextField();
        lblWarehouseName = new javax.swing.JLabel();
        txtFCPantryName = new javax.swing.JTextField();
        lblFoodItemID = new javax.swing.JLabel();
        txtReqQ = new javax.swing.JTextField();
        txtWarehousename = new javax.swing.JTextField();
        lblFoodItem = new javax.swing.JLabel();
        btnPUpdate = new javax.swing.JButton();
        lblFoodPmg = new javax.swing.JLabel();
        lblFCPantryname = new javax.swing.JLabel();
        lblitmId = new javax.swing.JLabel();
        lblFDitm1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblAddPantryTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddPantryTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblAddPantryTitle.setText("View/Modify Pantry Items");
        add(lblAddPantryTitle);
        lblAddPantryTitle.setBounds(320, 20, 410, 35);

        tblPItems.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblPItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Warehouse Name", "Pantry Name", "Pantry Manager", "Food Item", "Item Quantity"
            }
        ));
        tblPItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPItemsMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblPItems);

        add(jScrollPane);
        jScrollPane.setBounds(0, 80, 1140, 153);

        btnPEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnPEdit.setText("Edit");
        btnPEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPEditActionPerformed(evt);
            }
        });
        add(btnPEdit);
        btnPEdit.setBounds(960, 260, 92, 22);

        btnPDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnPDelete.setText("Delete");
        btnPDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDeleteActionPerformed(evt);
            }
        });
        add(btnPDelete);
        btnPDelete.setBounds(1050, 260, 92, 22);

        viewPanel.setOpaque(false);
        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFoodItem.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtFoodItem.setPreferredSize(new java.awt.Dimension(150, 25));
        txtFoodItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFoodItemFocusLost(evt);
            }
        });
        txtFoodItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodItemKeyReleased(evt);
            }
        });
        viewPanel.add(txtFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 137, -1));

        txtFCPManager.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtFCPManager.setPreferredSize(new java.awt.Dimension(150, 25));
        txtFCPManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCPManagerFocusLost(evt);
            }
        });
        txtFCPManager.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFCPManagerKeyReleased(evt);
            }
        });
        viewPanel.add(txtFCPManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 137, -1));

        lblWarehouseName.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseName.setText("Warehouse Name:");
        viewPanel.add(lblWarehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        txtFCPantryName.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtFCPantryName.setPreferredSize(new java.awt.Dimension(150, 25));
        txtFCPantryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCPantryNameFocusLost(evt);
            }
        });
        txtFCPantryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFCPantryNameKeyReleased(evt);
            }
        });
        viewPanel.add(txtFCPantryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 137, -1));

        lblFoodItemID.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        viewPanel.add(lblFoodItemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 20));

        txtReqQ.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtReqQ.setPreferredSize(new java.awt.Dimension(150, 25));
        txtReqQ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReqQFocusLost(evt);
            }
        });
        txtReqQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReqQKeyReleased(evt);
            }
        });
        viewPanel.add(txtReqQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 137, -1));

        txtWarehousename.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehousename.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehousename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehousenameFocusLost(evt);
            }
        });
        txtWarehousename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWarehousenameKeyReleased(evt);
            }
        });
        viewPanel.add(txtWarehousename, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 137, -1));

        lblFoodItem.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblFoodItem.setText("Food Item:");
        viewPanel.add(lblFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btnPUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnPUpdate.setText("Update");
        btnPUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPUpdateActionPerformed(evt);
            }
        });
        viewPanel.add(btnPUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 92, -1));

        lblFoodPmg.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblFoodPmg.setText("Pantry Manager:");
        viewPanel.add(lblFoodPmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        lblFCPantryname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblFCPantryname.setText("Pantry Name:");
        viewPanel.add(lblFCPantryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        lblitmId.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblitmId.setText("Item ID:");
        viewPanel.add(lblitmId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblFDitm1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblFDitm1.setText("Item Quantity:");
        viewPanel.add(lblFDitm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        viewPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, -1));

        add(viewPanel);
        viewPanel.setBounds(140, 250, 450, 410);
        add(LabelImage);
        LabelImage.setBounds(0, 0, 3220, 950);
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }

    public void makeTableTransparent() {
        tblPItems.setOpaque(false);
        ((DefaultTableCellRenderer) tblPItems.getDefaultRenderer(Object.class)).setOpaque(false);
        tblPItems.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblPItems.getModel().getColumnCount(); i++) {
            tblPItems.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    private void btnPEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPItems.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to Edit");
            return;
        }
        viewPanel.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tblPItems.getModel();
        FoodPantryItems selectedFCPI = (FoodPantryItems) model.getValueAt(selectedRowIndex, 0);
        lblFoodItemID.setText(selectedFCPI.getFcpitemid());
        txtWarehousename.setText(selectedFCPI.getFcpWHname());
        txtFCPantryName.setText(selectedFCPI.getPantryName());
        txtFCPManager.setText(selectedFCPI.getPantryManager());
        txtFoodItem.setText(selectedFCPI.getFoodItem());
        txtReqQ.setText(String.valueOf(selectedFCPI.getFoodQuan()));
    }//GEN-LAST:event_btnPEditActionPerformed

    private void btnPDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPItems.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPItems.getModel();
        FoodPantryItems selectedFCPI = (FoodPantryItems) model.getValueAt(selectedRowIndex, 0);
        /* // First delete the customer from employee
        this.system.getEmployeeDirectory().deleteEmployee(selectedRest.getResManagerName());
        // And thne delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAcc(
            this.system.getRestaurantDirectory().getResList().
            get(selectedRowIndex).getUserAcc()
        );
        // finally delete the user from customer directory*/
        //  ecosystem.getFCPDirectory().deleteFCPantry(selectedFCP);
        fcpid = ecosystem.getFCPIDirectory();
        fcpid.deleteFCPItems(selectedFCPI);
        ecosystem.setFCPIDirectory(fcpid);
        JOptionPane.showMessageDialog(this, "Pantry Item deleted Successfully");
        populatePantryItemsTable();
    }//GEN-LAST:event_btnPDeleteActionPerformed

    private void txtWarehousenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehousenameFocusLost
        // TODO add your handling code here:
        if (!(txtWarehousename.getText().matches("^[a-zA-Z]*$"))) {
            lblFoodPmg.setText("Invalid input. Please enter only alphabets");
        } else {
            lblFoodPmg.setText("");
        }
    }//GEN-LAST:event_txtWarehousenameFocusLost

    private void txtWarehousenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWarehousenameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarehousenameKeyReleased

    private void txtFCPantryNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCPantryNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCPantryNameFocusLost

    private void txtFCPantryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFCPantryNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCPantryNameKeyReleased

    private void txtFCPManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCPManagerFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCPManagerFocusLost

    private void txtFCPManagerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFCPManagerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCPManagerKeyReleased

    private void txtFoodItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFoodItemFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodItemFocusLost

    private void txtFoodItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodItemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodItemKeyReleased

    private void txtReqQFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReqQFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqQFocusLost

    private void txtReqQKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReqQKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqQKeyReleased

    private void btnPUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPItems.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPItems.getModel();
        String FCPid = lblFoodItemID.getText();
        ArrayList<FoodPantryItems> fcPantryItemsList = ecosystem.getFCPIDirectory().getFcpiList();
        for (FoodPantryItems f : fcPantryItemsList) {
            if (f.getFcpitemid().equals(FCPid)) {
                f.setFcpWHname(txtWarehousename.getText());
                f.setPantryName(txtFCPantryName.getText());
                f.setPantryManager(txtFCPManager.getText());
                f.setFoodItem(txtFoodItem.getText());
                f.setFoodQuan(txtReqQ.getText());
                //UserAccount FCPua=new UserAccount();
                //FCPua.setUsername(txtFCPuname.getText());
                //FCPua.setPassword(txtFCPpwd.getText());
                //f.setFcpAccount(FCPua);
            }

        }
        // ecosystem.setFCWDirectory(fcWarehouseList);
        JOptionPane.showMessageDialog(this, "Pantry Item details updated successfully");
        clearfields();
        populatePantryItemsTable();
        viewPanel.setVisible(false);
    }//GEN-LAST:event_btnPUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
       viewPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblPItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPItemsMousePressed
        // TODO add your handling code here:
        tblPItems.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblPItemsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPDelete;
    private javax.swing.JButton btnPEdit;
    private javax.swing.JButton btnPUpdate;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAddPantryTitle;
    private javax.swing.JLabel lblFCPantryname;
    private javax.swing.JLabel lblFDitm1;
    private javax.swing.JLabel lblFoodItem;
    private javax.swing.JLabel lblFoodItemID;
    private javax.swing.JLabel lblFoodPmg;
    private javax.swing.JLabel lblWarehouseName;
    private javax.swing.JLabel lblitmId;
    private javax.swing.JTable tblPItems;
    private javax.swing.JTextField txtFCPManager;
    private javax.swing.JTextField txtFCPantryName;
    private javax.swing.JTextField txtFoodItem;
    private javax.swing.JTextField txtReqQ;
    private javax.swing.JTextField txtWarehousename;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

    private void populatePantryItemsTable() {
        DefaultTableModel model = (DefaultTableModel) tblPItems.getModel();
        model.setRowCount(0);
        for (FoodPantryItems fcpi : ecosystem.getFCPIDirectory().getFcpiList()) {
            String fcpWhName = fcpi.getFcpWHname();
            System.out.println(fcpWhName + "satish ouside populatetbl");
            if(fcpWhName.equals(WHname)){
             System.out.println(fcpWhName + "satish inside populatetbl");
            Object[] row = new Object[6];
            row[0] = fcpi;
            row[1] = fcpi.getFcpWHname();
            row[2] = fcpi.getPantryName();
            row[3] = fcpi.getPantryManager();
            row[4] = fcpi.getFoodItem();
            row[5] = fcpi.getFoodQuan();
            model.addRow(row);
            }
        }
    }

    private void clearfields() {
        txtWarehousename.setText("");
        txtFCPantryName.setText("");
        txtFCPManager.setText("");
        txtFoodItem.setText("");
        txtReqQ.setText("");
        lblFoodItemID.setText("");
    }
}
