/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.FoodPantry.FoodPantry;
import Business.FoodWarehouse.FoodWarehouse;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lokavarapusatishkumar
 */
public class ContactWarehousePanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactWarehousePanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String WHname;
    String FCPmgname;
    public ContactWarehousePanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        lblRequestVol.setVisible(false);
        lblVolReq.setVisible(false);
        cbVolReq.setVisible(false);
        btnSubmitReq.setVisible(false);
        FCPmgname = userAcc.getEmployee().getName();
        for(FoodPantry fcp: ecosystem.getFCPDirectory().getFcpList()){
            if(fcp.getFcpManager().equals(FCPmgname)){
                 WHname = fcp.getFcpWHname();
            }
        }
        setBG();
        populatefields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFCWarehouseTitle = new javax.swing.JLabel();
        txtWarehouseFCAdmin = new javax.swing.JTextField();
        lblWarehousename = new javax.swing.JLabel();
        txtWarehousename = new javax.swing.JTextField();
        lblWarehousePhone = new javax.swing.JLabel();
        txtWarehousePhone = new javax.swing.JTextField();
        lblWarehouseAdd = new javax.swing.JLabel();
        txtWarehouseAdd = new javax.swing.JTextField();
        lblWarehouseCity = new javax.swing.JLabel();
        txtWarehouseCity = new javax.swing.JTextField();
        lblWarehouseState = new javax.swing.JLabel();
        txtWarehouseState = new javax.swing.JTextField();
        lblWarehouseZip = new javax.swing.JLabel();
        txtWarehouseZip = new javax.swing.JTextField();
        lblWarehouseFCAdmin = new javax.swing.JLabel();
        cbVolReq = new javax.swing.JComboBox<>();
        btnSubmitReq = new javax.swing.JButton();
        lblVolReq = new javax.swing.JLabel();
        lblRequestVol = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFCWarehouseTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblFCWarehouseTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblFCWarehouseTitle.setText("Food Cloud Warehouse");
        add(lblFCWarehouseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 19, -1, -1));

        txtWarehouseFCAdmin.setEditable(false);
        txtWarehouseFCAdmin.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehouseFCAdmin.setEnabled(false);
        txtWarehouseFCAdmin.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseFCAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehouseFCAdminFocusLost(evt);
            }
        });
        add(txtWarehouseFCAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 137, -1));

        lblWarehousename.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehousename.setText("Warehouse Name :");
        add(lblWarehousename, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 92, -1, -1));

        txtWarehousename.setEditable(false);
        txtWarehousename.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehousename.setEnabled(false);
        txtWarehousename.setOpaque(true);
        txtWarehousename.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehousename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehousenameFocusLost(evt);
            }
        });
        add(txtWarehousename, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 88, 137, -1));

        lblWarehousePhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehousePhone.setText("Phone Number :");
        add(lblWarehousePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 135, -1, -1));

        txtWarehousePhone.setEditable(false);
        txtWarehousePhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehousePhone.setEnabled(false);
        txtWarehousePhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehousePhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehousePhoneFocusLost(evt);
            }
        });
        add(txtWarehousePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 131, 137, -1));

        lblWarehouseAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseAdd.setText("Address :");
        add(lblWarehouseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 178, -1, -1));

        txtWarehouseAdd.setEditable(false);
        txtWarehouseAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehouseAdd.setEnabled(false);
        txtWarehouseAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtWarehouseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 174, 137, -1));

        lblWarehouseCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseCity.setText("City :");
        add(lblWarehouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 221, -1, -1));

        txtWarehouseCity.setEditable(false);
        txtWarehouseCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehouseCity.setEnabled(false);
        txtWarehouseCity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarehouseCityActionPerformed(evt);
            }
        });
        add(txtWarehouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 217, 137, -1));

        lblWarehouseState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseState.setText("State :");
        add(lblWarehouseState, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 264, -1, -1));

        txtWarehouseState.setEditable(false);
        txtWarehouseState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehouseState.setEnabled(false);
        txtWarehouseState.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtWarehouseState, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 260, 137, -1));

        lblWarehouseZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseZip.setText("Zipcode :");
        add(lblWarehouseZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        txtWarehouseZip.setEditable(false);
        txtWarehouseZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtWarehouseZip.setEnabled(false);
        txtWarehouseZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehouseZipFocusLost(evt);
            }
        });
        add(txtWarehouseZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 137, -1));

        lblWarehouseFCAdmin.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblWarehouseFCAdmin.setText("Food Cloud Admin :");
        add(lblWarehouseFCAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        cbVolReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbVolReq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "10", "20", "30", "40", "50" }));
        add(cbVolReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 132, -1));

        btnSubmitReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnSubmitReq.setText("Submit Request");
        btnSubmitReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitReqActionPerformed(evt);
            }
        });
        add(btnSubmitReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        lblVolReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolReq.setText("Number of Volunteers Required :");
        add(lblVolReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        lblRequestVol.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblRequestVol.setText("Request Volunteers");
        add(lblRequestVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 700));
    }// </editor-fold>//GEN-END:initComponents

       public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }
    private void txtWarehouseFCAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehouseFCAdminFocusLost
        // TODO add your handling code here:
//        if(!(txtWHFCAdmin.getText().matches("^[a-zA-Z]*$"))){
//            lblWHFCAdmin1.setText("Invalid input. Please enter only alphabets.");
//        }
//        else{
//            lblWHFCAdmin1.setText("");
//        }
    }//GEN-LAST:event_txtWarehouseFCAdminFocusLost

    private void txtWarehousenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehousenameFocusLost
        // TODO add your handling code here:
//        if(!(txtWHname.getText().matches("^[a-zA-Z]*$"))){
//            lblWHname1.setText("Invalid input. Please enter only alphabets");
//        }
//        else{
//            lblWHname1.setText("");
//        }
    }//GEN-LAST:event_txtWarehousenameFocusLost

    private void txtWarehousePhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehousePhoneFocusLost
        // TODO add your handling code here:
//        if(!(txtWHPhno.getText().matches("^[0-9]*$")) || !(txtWHPhno.getText().length()==10)) {
//            lblWHPhno1.setText("Please enter a valid phone number");
//        }
//        else{
//            lblWHPhno1.setText("");
//
//        }
    }//GEN-LAST:event_txtWarehousePhoneFocusLost

    private void txtWarehouseZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehouseZipFocusLost
        // TODO add your handling code here:
//        if((txtWHZip.getText().matches("^[a-zA-Z]*$"))){
//            lblWHZip1.setText("Invalid input. Please enter only numbers");
//        }
//        else{
//            lblWHZip1.setText("");
//        }
    }//GEN-LAST:event_txtWarehouseZipFocusLost

    private void btnSubmitReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitReqActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Your request has been sent to Warehouse");
    }//GEN-LAST:event_btnSubmitReqActionPerformed

    private void txtWarehouseCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarehouseCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarehouseCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnSubmitReq;
    private javax.swing.JComboBox<String> cbVolReq;
    private javax.swing.JLabel lblFCWarehouseTitle;
    private javax.swing.JLabel lblRequestVol;
    private javax.swing.JLabel lblVolReq;
    private javax.swing.JLabel lblWarehouseAdd;
    private javax.swing.JLabel lblWarehouseCity;
    private javax.swing.JLabel lblWarehouseFCAdmin;
    private javax.swing.JLabel lblWarehousePhone;
    private javax.swing.JLabel lblWarehouseState;
    private javax.swing.JLabel lblWarehouseZip;
    private javax.swing.JLabel lblWarehousename;
    private javax.swing.JTextField txtWarehouseAdd;
    private javax.swing.JTextField txtWarehouseCity;
    private javax.swing.JTextField txtWarehouseFCAdmin;
    private javax.swing.JTextField txtWarehousePhone;
    private javax.swing.JTextField txtWarehouseState;
    private javax.swing.JTextField txtWarehouseZip;
    private javax.swing.JTextField txtWarehousename;
    // End of variables declaration//GEN-END:variables

    private void populatefields() {
        for(FoodWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwName().equals(WHname)){
                txtWarehousename.setText(fcw.getFcwName());
                txtWarehousePhone.setText(fcw.getFcwPhno());
                txtWarehouseAdd.setText(fcw.getFcwAddres());
                txtWarehouseCity.setText(fcw.getFcwCity());
                txtWarehouseState.setText(fcw.getFcwState());
                txtWarehouseZip.setText(fcw.getFcwZipcode());
                txtWarehouseFCAdmin.setText(fcw.getFcwAdmin());
            }
        }
    }

}
