/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.FoodPantry.FoodPantryItems;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lokavarapusatishkumar
 */
public class PantryStockPanel extends javax.swing.JPanel {

    /**
     * Creates new form PantryStockPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    public PantryStockPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        populatePantryItemsTable();
         lblQReqF.setVisible(false);
         lblPersons.setVisible(false);
         cbQReqF.setVisible(false);
         btnSubReq.setVisible(false);
         chkReqFWH.setVisible(false);
         setBG();
         makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvailStockTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblAvailStock = new javax.swing.JTable();
        btnSubReq = new javax.swing.JButton();
        lblQReqF = new javax.swing.JLabel();
        cbQReqF = new javax.swing.JComboBox<>();
        chkReqFWH = new javax.swing.JCheckBox();
        lblPersons = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvailStockTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAvailStockTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblAvailStockTitle.setText("Available Stock");
        add(lblAvailStockTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        tblAvailStock.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblAvailStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item ID", "Food Item", "Item Quantity"
            }
        ));
        tblAvailStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAvailStockMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblAvailStock);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1008, 153));

        btnSubReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnSubReq.setText("Submit Request");
        btnSubReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubReqActionPerformed(evt);
            }
        });
        add(btnSubReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 369, -1, -1));

        lblQReqF.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblQReqF.setText("Quantity Required for:");
        add(lblQReqF, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 315, -1, -1));

        cbQReqF.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbQReqF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "50", "100", "150", "200", "250" }));
        add(cbQReqF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 120, -1));

        chkReqFWH.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        chkReqFWH.setText("Request stock from Warehouse");
        chkReqFWH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReqFWHActionPerformed(evt);
            }
        });
        add(chkReqFWH, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        lblPersons.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblPersons.setText("Persons");
        add(lblPersons, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 690));
    }// </editor-fold>//GEN-END:initComponents

    
       public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }

    public void makeTableTransparent() {
        tblAvailStock.setOpaque(false);
        ((DefaultTableCellRenderer) tblAvailStock.getDefaultRenderer(Object.class)).setOpaque(false);
        tblAvailStock.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblAvailStock.getModel().getColumnCount(); i++) {
            tblAvailStock.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    private void chkReqFWHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReqFWHActionPerformed
        // TODO add your handling code here:
        if(chkReqFWH.isSelected()){
            lblQReqF.setVisible(true);
            lblPersons.setVisible(true);
            cbQReqF.setVisible(true);
            btnSubReq.setVisible(true);
        }
        else{
            lblQReqF.setVisible(false);
            lblPersons.setVisible(false);
            cbQReqF.setVisible(false);
            btnSubReq.setVisible(false);
        }
    }//GEN-LAST:event_chkReqFWHActionPerformed

    private void btnSubReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubReqActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Your request has been sent to Warehouse");
    }//GEN-LAST:event_btnSubReqActionPerformed

    private void tblAvailStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAvailStockMousePressed
        // TODO add your handling code here:
        tblAvailStock.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblAvailStockMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnSubReq;
    private javax.swing.JComboBox<String> cbQReqF;
    private javax.swing.JCheckBox chkReqFWH;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAvailStockTitle;
    private javax.swing.JLabel lblPersons;
    private javax.swing.JLabel lblQReqF;
    private javax.swing.JTable tblAvailStock;
    // End of variables declaration//GEN-END:variables

    private void populatePantryItemsTable() {
        DefaultTableModel model = (DefaultTableModel) tblAvailStock.getModel();
        model.setRowCount(0);
        System.out.println(ecosystem.getFCPIDirectory().getFcpiList());
        System.out.println( "ddfgsdfgsdgfsdgs");
        for(FoodPantryItems fcpi: ecosystem.getFCPIDirectory().getFcpiList()){
            System.out.println(fcpi.getPantryManager() + "dfsdgs");
            if(fcpi.getPantryManager().equals(userAcc.getEmployee().getName())){
           Object[] row = new Object[3];
           row[0] =fcpi;
           row[1] =fcpi.getFoodItem();
           row[2] =fcpi.getFoodQuan();
           model.addRow(row);
            }
        } 
    }
}
