/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.VolunteerRole;

import Business.FoodDonation.FoodDonation;
import Business.FoodDonation.FoodDonationDirectory;
import Business.EcoSystem;
import Business.FoodPantry.FoodPantryItems;
import Business.NonGovtOrgVolunteer.NGOVolunteer;
import Business.FoodRequestorder.FoodRequestorder;
import Business.FoodRequestorder.FoodRequestorderDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import userinterface.DonorRole.DonorAreaJPanel;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.MainJFrame;

/**
 *
 * @author sivanagendrakanakababumarada
 */
public class VolunteerWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    JPanel jp;
    JSplitPane jsp;
    String name;

    public VolunteerWorkAreaPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        System.out.println(userAccount);
        System.out.println(userAccount.getEmployee().getName());
        this.ecosystem = ecosystem;
        this.jp = jp;
        this.jsp = jsp;
        name = userAccount.getEmployee().getName();

         if(ecosystem.getDonatDirectory()== null){
         ecosystem.setDonatDirectory(new FoodDonationDirectory());
        }
         if (ecosystem.getReqorderDirectory() == null) {
            ecosystem.setReqorderDirectory(new FoodRequestorderDirectory());
        }

        setBG();
        logoutlogo();
        makeTableTransparent();
        makeTableTransparent1();
        setLogo();
        
        populatePickupTable();
        populateDelTable();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tblPickupReq = new javax.swing.JTable();
        lblFCRProfileTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonationPick = new javax.swing.JTable();
        lblPickupReqTitle1 = new javax.swing.JLabel();
        lblDeliveryReqTitle = new javax.swing.JLabel();
        btnDonAcceptPickup = new javax.swing.JButton();
        btnDonProcessPickup = new javax.swing.JButton();
        btnDonAcceptDel = new javax.swing.JButton();
        btnDonProcessDel = new javax.swing.JButton();
        lblDonlogout = new javax.swing.JLabel();
        logoImg = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPickupReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Requestor", "Address", "City", "Zip Code", "Status"
            }
        ));
        tblPickupReq.setOpaque(false);
        tblPickupReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPickupReqMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblPickupReq);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 389, 1008, 153));

        lblFCRProfileTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblFCRProfileTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblFCRProfileTitle.setText("Food Cloud Requests");
        add(lblFCRProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 340, -1));

        tblDonationPick.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblDonationPick.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Donation ID", "Donor", "Address", "City", "Zip Code", "Status"
            }
        ));
        tblDonationPick.setOpaque(false);
        tblDonationPick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDonationPickMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDonationPick);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1008, 153));

        lblPickupReqTitle1.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        lblPickupReqTitle1.setForeground(new java.awt.Color(0, 153, 204));
        lblPickupReqTitle1.setText("Pickup Requests");
        add(lblPickupReqTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        lblDeliveryReqTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        lblDeliveryReqTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblDeliveryReqTitle.setText("Delivery Requests");
        add(lblDeliveryReqTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, 220, -1));

        btnDonAcceptPickup.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnDonAcceptPickup.setText("Accept");
        btnDonAcceptPickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonAcceptPickupActionPerformed(evt);
            }
        });
        add(btnDonAcceptPickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        btnDonProcessPickup.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnDonProcessPickup.setText("Process");
        btnDonProcessPickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonProcessPickupActionPerformed(evt);
            }
        });
        add(btnDonProcessPickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        btnDonAcceptDel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnDonAcceptDel.setText("Accept");
        btnDonAcceptDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonAcceptDelActionPerformed(evt);
            }
        });
        add(btnDonAcceptDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 560, -1, -1));

        btnDonProcessDel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnDonProcessDel.setText("Process");
        btnDonProcessDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonProcessDelActionPerformed(evt);
            }
        });
        add(btnDonProcessDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 560, -1, -1));

        lblDonlogout.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDonlogoutMousePressed(evt);
            }
        });
        add(lblDonlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 40, 30));
        add(logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 60));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 790));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void logoutlogo() {

        try {

            lblDonlogout.setMinimumSize(new Dimension(50, 60));
            lblDonlogout.setPreferredSize(new Dimension(50, 60));
            lblDonlogout.setMaximumSize(new Dimension(50, 60));

            Image img1 = ImageIO.read(getClass().getResource("/Images/signout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lblDonlogout.setIcon(new ImageIcon(newimg1));

        } catch (IOException ex) {
            Logger.getLogger(DonorAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public void makeTableTransparent() {
        tblDonationPick.setOpaque(false);
        ((DefaultTableCellRenderer) tblDonationPick.getDefaultRenderer(Object.class)).setOpaque(false);
        tblDonationPick.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblDonationPick.getModel().getColumnCount(); i++) {
            tblDonationPick.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    public void makeTableTransparent1() {
        tblPickupReq.setOpaque(false);
        ((DefaultTableCellRenderer) tblPickupReq.getDefaultRenderer(Object.class)).setOpaque(false);
        tblPickupReq.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblPickupReq.getModel().getColumnCount(); i++) {
            tblPickupReq.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
      public void setLogo() {
        try {
            logoImg.setMinimumSize(new Dimension(100, 100));
            logoImg.setPreferredSize(new Dimension(100, 100));
            logoImg.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnDonAcceptPickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonAcceptPickupActionPerformed

        int selectedRow = tblDonationPick.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        FoodDonation dt = (FoodDonation) tblDonationPick.getValueAt(selectedRow, 0);
        //        order.setDeliveryMan(userAccount.getEmployee().getName());
        if (dt.getDonatStatus().equals("Assigned to Volunteer")) {
            dt.setDonatStatus("Order Picked up");
        } else {
            JOptionPane.showMessageDialog(null, "Order is accpeted or completed already");
        }
        populatePickupTable();
    }//GEN-LAST:event_btnDonAcceptPickupActionPerformed

    private void btnDonProcessPickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonProcessPickupActionPerformed

        int selectedRow = tblDonationPick.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        FoodDonation dt = (FoodDonation) tblDonationPick.getValueAt(selectedRow, 0);
        if (dt.getDonatStatus().equals("Delivered")) {
            JOptionPane.showMessageDialog(null, "Already Delivered.");
            return;
        } else if (dt.getDonatStatus().equals("Order Picked up")) {
            dt.setDonatStatus("Delivered");
            for (NGOVolunteer v : ecosystem.getVolDir().getVolunteerList()) {
                if (v.getVolName().equals(name)) {
                    v.setVolAvail("Yes");
                }
            }
            FoodPantryItems curPantryItem = new FoodPantryItems();
            
//            ecosystem.getFCPIDirectory().addFCPItems(curPantryItem);
            JOptionPane.showMessageDialog(null, "Delivered Order with id : " + dt.getDonatId());
            populatePickupTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please accept the order first");
        }

        //orderDirectory.getOrderDirectory().remove(order);

    }//GEN-LAST:event_btnDonProcessPickupActionPerformed

    private void btnDonAcceptDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonAcceptDelActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPickupReq.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        FoodRequestorder rq = (FoodRequestorder) tblPickupReq.getValueAt(selectedRow, 0);
        //        order.setDeliveryMan(userAccount.getEmployee().getName());
        if (rq.getReqOrderStatus().equals("Assigned to Volunteer")) {
            rq.setReqOrderStatus("Order Picked up");
        } else {
            JOptionPane.showMessageDialog(null, "Order is accpeted or completed already");
        }
        populateDelTable();

    }//GEN-LAST:event_btnDonAcceptDelActionPerformed

    private void btnDonProcessDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonProcessDelActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPickupReq.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        FoodRequestorder rq = (FoodRequestorder) tblPickupReq.getValueAt(selectedRow, 0);
        if (rq.getReqOrderStatus().equals("Delivered")) {
            JOptionPane.showMessageDialog(null, "Already Delivered.");
            return;
        } else if (rq.getReqOrderStatus().equals("Order Picked up")) {
            rq.setReqOrderStatus("Delivered");
            for (NGOVolunteer v : ecosystem.getVolDir().getVolunteerList()) {
                if (v.getVolName().equals(name)) {
                    v.setVolAvail("Yes");
                }
            }
            JOptionPane.showMessageDialog(null, "Delivered Order with id : " + rq.getReqOrderId());
            populateDelTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please accept the order first");
        }
    }//GEN-LAST:event_btnDonProcessDelActionPerformed

    private void lblDonlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonlogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_lblDonlogoutMousePressed

    private void tblDonationPickMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonationPickMousePressed
        // TODO add your handling code here:
              tblDonationPick.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblDonationPickMousePressed

    private void tblPickupReqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPickupReqMousePressed
        // TODO add your handling code here:
              tblPickupReq.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblPickupReqMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnDonAcceptDel;
    private javax.swing.JButton btnDonAcceptPickup;
    private javax.swing.JButton btnDonProcessDel;
    private javax.swing.JButton btnDonProcessPickup;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeliveryReqTitle;
    private javax.swing.JLabel lblDonlogout;
    private javax.swing.JLabel lblFCRProfileTitle;
    private javax.swing.JLabel lblPickupReqTitle1;
    private javax.swing.JLabel logoImg;
    private javax.swing.JTable tblDonationPick;
    private javax.swing.JTable tblPickupReq;
    // End of variables declaration//GEN-END:variables

    private void populatePickupTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonationPick.getModel();
        model.setRowCount(0);
        System.out.print(ecosystem.getDonatDirectory().getDonatList());
        for (FoodDonation dt : ecosystem.getDonatDirectory().getDonatList()) {
            System.out.println(dt + "volingz");
            System.out.println(dt.getDonatVol() + "nee");
            if (dt.getDonatVol() != null) {
                if (dt.getDonatVol().equals(userAccount.getEmployee().getName())) {
                    Object[] row = new Object[6];
                    row[0] = dt;
                    row[1] = dt.getDonatDname();
                    row[2] = dt.getDonatAdd();
                    row[3] = dt.getDonatCity();
                    row[4] = dt.getDonatZip();
                    row[5] = dt.getDonatStatus();
                    model.addRow(row);
                }
            }
        }
    }

    private void populateDelTable() {
        DefaultTableModel model = (DefaultTableModel) tblPickupReq.getModel();
        model.setRowCount(0);
        
        for(FoodRequestorder rq: ecosystem.getReqorderDirectory().getReqOrderList()){
            if(rq.getReqVol() != null  && rq.getReqVol().equals(userAccount.getEmployee().getName())){
           Object[] row = new Object[6];
           row[0] =rq;
           row[1] =rq.getReqName();
           row[2] =rq.getReqAdd();
           row[3] =rq.getReqCity();
           row[4] =rq.getReqZip();
           row[5] =rq.getReqOrderStatus();
           model.addRow(row);
            }
        }
    }
}
