/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Worker.Worker;
import Business.NonGovtOrgVolunteer.NGOVolunteer;
import Business.NonGovtOrgVolunteer.NGOVolunteerDirectory;
import Business.Role.DeliveryVolunteer;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sivanagendrakanakababumarada
 */
public class AddVolunteerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVolunteerPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory uad;
    NGOVolunteerDirectory vold;
    String nogName;

    public AddVolunteerPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if (ecosystem.getVolDir() == null) {
            ecosystem.setVolDir(new NGOVolunteerDirectory());
        }
        setBG();
        nogName = userAcc.getEmployee().getName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddVolunteerTitle = new javax.swing.JLabel();
        lblVolunteername = new javax.swing.JLabel();
        txtVolunteername = new javax.swing.JTextField();
        lblVolunteerPhone = new javax.swing.JLabel();
        txtVolunteerPhone = new javax.swing.JTextField();
        lblVolunteerAdd = new javax.swing.JLabel();
        txtVolunteerAdd = new javax.swing.JTextField();
        lblVolunteerCity = new javax.swing.JLabel();
        txtVolunteerCity = new javax.swing.JTextField();
        lblVolunteerState = new javax.swing.JLabel();
        txtVolunteerState = new javax.swing.JTextField();
        lblVolunteerZip = new javax.swing.JLabel();
        txtVolunteerZip = new javax.swing.JTextField();
        lblVolunteerExp = new javax.swing.JLabel();
        txtVolunteerExp = new javax.swing.JTextField();
        lblVolunteeruname = new javax.swing.JLabel();
        txtVolunteeruname = new javax.swing.JTextField();
        lblVolunteerpwd = new javax.swing.JLabel();
        txtVolunteerpwd = new javax.swing.JTextField();
        lblVolunteercopwd1 = new javax.swing.JLabel();
        txtVolunteercopwd1 = new javax.swing.JTextField();
        btnVolSubmit = new javax.swing.JButton();
        lblVolunteerid = new javax.swing.JLabel();
        txtVolunteerid = new javax.swing.JTextField();
        lblVolunteerage = new javax.swing.JLabel();
        txtVolunteerage = new javax.swing.JTextField();
        lblVolunteerid2 = new javax.swing.JLabel();
        lblVolunteername1 = new javax.swing.JLabel();
        lblVolunteerPhno1 = new javax.swing.JLabel();
        lblVolunterZip1 = new javax.swing.JLabel();
        lblVolunteerpwd2 = new javax.swing.JLabel();
        lblVolunteerAdmin1 = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddVolunteerTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddVolunteerTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblAddVolunteerTitle.setText("Add Volunteer");
        add(lblAddVolunteerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 6, -1, -1));

        lblVolunteername.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteername.setText("Volunteer Name:");
        add(lblVolunteername, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 104, -1, -1));

        txtVolunteername.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteername.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteernameFocusLost(evt);
            }
        });
        txtVolunteername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteernameActionPerformed(evt);
            }
        });
        add(txtVolunteername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 137, -1));

        lblVolunteerPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerPhone.setText("Phone Number:");
        add(lblVolunteerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 190, -1, -1));

        txtVolunteerPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteerPhoneFocusLost(evt);
            }
        });
        add(txtVolunteerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 186, 137, -1));

        lblVolunteerAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerAdd.setText("Address:");
        add(lblVolunteerAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 233, -1, -1));

        txtVolunteerAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerAddActionPerformed(evt);
            }
        });
        add(txtVolunteerAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 229, 137, -1));

        lblVolunteerCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerCity.setText("City:");
        add(lblVolunteerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 276, -1, -1));

        txtVolunteerCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtVolunteerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 272, 137, -1));

        lblVolunteerState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerState.setText("State:");
        add(lblVolunteerState, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 319, -1, -1));

        txtVolunteerState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerState.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtVolunteerState, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 315, 137, -1));

        lblVolunteerZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerZip.setText("Zip:");
        add(lblVolunteerZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        txtVolunteerZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteerZipFocusLost(evt);
            }
        });
        add(txtVolunteerZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 358, 137, -1));

        lblVolunteerExp.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerExp.setText("Volunteer Experience:");
        add(lblVolunteerExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 405, -1, -1));

        txtVolunteerExp.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerExp.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerExp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteerExpFocusLost(evt);
            }
        });
        txtVolunteerExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerExpActionPerformed(evt);
            }
        });
        add(txtVolunteerExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 401, 137, -1));

        lblVolunteeruname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteeruname.setText("Volunteer Username:");
        add(lblVolunteeruname, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 448, -1, -1));

        txtVolunteeruname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteeruname.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtVolunteeruname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 444, 137, -1));

        lblVolunteerpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerpwd.setText("Password:");
        add(lblVolunteerpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 491, -1, -1));

        txtVolunteerpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtVolunteerpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 487, 137, -1));

        lblVolunteercopwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteercopwd1.setText("Confirm Password:");
        add(lblVolunteercopwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 534, -1, -1));

        txtVolunteercopwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteercopwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteercopwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteercopwd1FocusLost(evt);
            }
        });
        add(txtVolunteercopwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 137, -1));

        btnVolSubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnVolSubmit.setText("Submit");
        btnVolSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolSubmitActionPerformed(evt);
            }
        });
        add(btnVolSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        lblVolunteerid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerid.setText("Volunteer ID:");
        add(lblVolunteerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 61, -1, -1));

        txtVolunteerid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteeridFocusLost(evt);
            }
        });
        txtVolunteerid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVolunteeridKeyReleased(evt);
            }
        });
        add(txtVolunteerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 57, 134, -1));

        lblVolunteerage.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolunteerage.setText("Volunteer Age:");
        add(lblVolunteerage, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 147, -1, -1));

        txtVolunteerage.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtVolunteerage.setPreferredSize(new java.awt.Dimension(150, 25));
        txtVolunteerage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVolunteerageFocusLost(evt);
            }
        });
        add(txtVolunteerage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 143, 137, -1));

        lblVolunteerid2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunteerid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 57, -1, -1));

        lblVolunteername1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunteername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 100, -1, -1));

        lblVolunteerPhno1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunteerPhno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 186, -1, -1));

        lblVolunterZip1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunterZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 358, -1, -1));

        lblVolunteerpwd2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunteerpwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 530, -1, -1));

        lblVolunteerAdmin1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblVolunteerAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 401, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 6, 1390, 790));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1650, 850, java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(AddVolunteerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtVolunteernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteernameFocusLost
        // TODO add your handling code here:
        if (!(txtVolunteername.getText().matches("^[a-zA-Z]*$"))) {
            lblVolunteername1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblVolunteername1.setText("");
        }
    }//GEN-LAST:event_txtVolunteernameFocusLost

    private void txtVolunteerPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteerPhoneFocusLost
        // TODO add your handling code here:
        if (!(txtVolunteerPhone.getText().matches("^[0-9]*$")) || !(txtVolunteerPhone.getText().length() == 10)) {
            lblVolunteerPhno1.setText("Please enter a valid phone number");
        } else {
            lblVolunteerPhno1.setText("");

        }
    }//GEN-LAST:event_txtVolunteerPhoneFocusLost

    private void txtVolunteerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerAddActionPerformed

    private void txtVolunteerZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteerZipFocusLost
        // TODO add your handling code here:
        if ((txtVolunteerZip.getText().matches("^[a-zA-Z]*$"))) {
            lblVolunterZip1.setText("Invalid input. Please enter only numbers");
        } else {
            lblVolunterZip1.setText("");
        }
    }//GEN-LAST:event_txtVolunteerZipFocusLost

    private void txtVolunteerExpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteerExpFocusLost
        // TODO add your handling code here:
//        if(!(txtVolExp.getText().matches("^[a-zA-Z]*$"))){
//            lblVolAdmin1.setText("Invalid input. Please enter only alphabets.");
//        }
//        else{
//            lblVolAdmin1.setText("");
//        }
    }//GEN-LAST:event_txtVolunteerExpFocusLost

    private void txtVolunteercopwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteercopwd1FocusLost
        // TODO add your handling code here:
//        if(!(txtVolpwd.getText().equals(txtVolcopwd1.getText()))){
//            lblVolpwd2.setText("Password Mismatch. Please verify the password entered.");
//        }
//        else{
//            lblVolpwd2.setText("");
//        }
    }//GEN-LAST:event_txtVolunteercopwd1FocusLost

    public boolean isValid(String test, String regex) {
//        String regex = "^[A-Za-z0-9]+";
        Pattern p = Pattern.compile(regex);

        if (test == null) {
            return false;
        }

        Matcher m = p.matcher(test);

        return m.matches();
    }
    
    public Integer tryParse(String text) {

        try {
            return Integer.valueOf(text);
        } catch (NumberFormatException e) {
            return -1;
        }

    }
    
    private void btnVolSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolSubmitActionPerformed
        // TODO add your handling code here:
        if (!nullCheck()) {
            if (chkpwd()) {

                String volId = txtVolunteerid.getText();
                String volName = txtVolunteername.getText();
                Integer volAge = tryParse(txtVolunteerage.getText());
                
                String phone = txtVolunteerPhone.getText();
                String volAdds = txtVolunteerAdd.getText();
                String volCity = txtVolunteerCity.getText();
                String volState = txtVolunteerState.getText();
                String volZip = txtVolunteerZip.getText();
                Integer volExp = tryParse(txtVolunteerExp.getText());
                String volUser = txtVolunteeruname.getText();
                String volPswd = txtVolunteerpwd.getText();
                
                
                if (!isValid(volId, "^[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid ID");
                    return;
                }
                if (!isValid(volName, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid name");
                    return;
                }
                if (volAge < 0) {
                    JOptionPane.showMessageDialog(this, "Please enter valid Age");
                    return;
                }
                if (!isValid(phone, "[+]?[0-9]{10,13}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid phone number");
                    return;
                }
                if (volAdds.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter volunteer address");
                    return;
                }
                if (!isValid(volCity, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid city");
                    return;
                }
                if (!isValid(volState, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){2,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid state");
                    return;
                }
                if (!isValid(volZip, "^[0-9]{5}(?:-[0-9]{4})?$")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid zip");
                    return;
                }
                if (volExp < 0) {
                    JOptionPane.showMessageDialog(this, "Please enter valid experience");
                    return;
                }
                if (!isValid(volUser, "^[a-zA-Z0-9._-]{6,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid username of atleast 6 characters");
                    return;
                }
                if (!isValid(volPswd, "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password of atleast 8 characters in length. It must contain a number, a specicial character, a lowercase and an uppercase character.");
                    return;
                }
                

                UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
                Worker employee = new Worker();
                employee.setName(txtVolunteername.getText());
                String role = "Volunteer";
                NGOVolunteer vol = new NGOVolunteer();
                vol.setVolId("volunteer" + txtVolunteerid.getText());
                vol.setVolName(txtVolunteername.getText());
                vol.setVolAge(txtVolunteerage.getText());
                vol.setVolPhno(txtVolunteerPhone.getText());
                vol.setVolAddress(txtVolunteerAdd.getText());
                vol.setVolCity(txtVolunteerCity.getText());
                vol.setVolState(txtVolunteerState.getText());
                vol.setVolZipcode(txtVolunteerZip.getText());
                vol.setVolExp(txtVolunteerExp.getText());
                UserAccount volAccount = new UserAccount();
                volAccount.setUsername(txtVolunteeruname.getText());
                volAccount.setPassword(txtVolunteerpwd.getText());
                // uaList.createUserAccount(txtFCAuname.getText(), txtFCApwd.getText(), employee, new FCAdminRole());
                //                ua = usersList.getUserAccount(txtUserName.getText());

                volAccount.setRole(new DeliveryVolunteer());
                volAccount.setEmployee(employee);
                vol.setVolAvail("New");
                vol.setVolNGO(nogName);
                uad = ecosystem.getUserAccountDirectory();
                uad.createUserAccount(txtVolunteeruname.getText(), txtVolunteerpwd.getText(), employee, new DeliveryVolunteer());
                ecosystem.setUserAccountDirectory(uad);
                vol.setVolAccount(volAccount);
                vold = ecosystem.getVolDir();
                vold.addNewVolunteer(vol);
                ecosystem.setVolDir(vold);
                Integer volCnt = ecosystem.getVolunteersCnt();
                ecosystem.setVolunteersCnt(volCnt + 1);
                JOptionPane.showMessageDialog(this, "Volunteer added successfully!");
                clearfields();
            } else {
                JOptionPane.showMessageDialog(this, "Password Mismatch. Please verify the password entered.");
                txtVolunteercopwd1.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnVolSubmitActionPerformed

    private void txtVolunteeridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteeridFocusLost
        // TODO add your handling code here:
        if ((txtVolunteerid.getText().matches("^[a-zA-Z]*$"))) {
            lblVolunteerid2.setText("Invalid input. Please enter only numbers");
        } else {
            lblVolunteerid2.setText("");
        }
    }//GEN-LAST:event_txtVolunteeridFocusLost

    private void txtVolunteeridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVolunteeridKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteeridKeyReleased

    private void txtVolunteerageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVolunteerageFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerageFocusLost

    private void txtVolunteerExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerExpActionPerformed

    private void txtVolunteernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteernameActionPerformed

    private boolean nullCheck() {
        if (txtVolunteerid.getText().length() != 0 && txtVolunteername.getText().length() != 0
                && txtVolunteerPhone.getText().length() != 0 && txtVolunteerAdd.getText().length() != 0 && txtVolunteerCity.getText().length() != 0
                && txtVolunteerState.getText().length() != 0 && txtVolunteerZip.getText().length() != 0 && txtVolunteerExp.getText().length() != 0
                && txtVolunteeruname.getText().length() != 0 && txtVolunteerpwd.getText().length() != 0 && txtVolunteercopwd1.getText().length() != 0) {
            return false;
        } else {
            return true;
        }
    }

    private void clearfields() {
        txtVolunteername.setText("");
        txtVolunteerPhone.setText("");
        txtVolunteerAdd.setText("");
        txtVolunteerCity.setText("");
        txtVolunteerState.setText("");
        txtVolunteerZip.setText("");
        txtVolunteerExp.setText("");
        txtVolunteeruname.setText("");
        txtVolunteerage.setText("");
        txtVolunteerpwd.setText("");
        txtVolunteercopwd1.setText("");
        txtVolunteerid.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnVolSubmit;
    private javax.swing.JLabel lblAddVolunteerTitle;
    private javax.swing.JLabel lblVolunteerAdd;
    private javax.swing.JLabel lblVolunteerAdmin1;
    private javax.swing.JLabel lblVolunteerCity;
    private javax.swing.JLabel lblVolunteerExp;
    private javax.swing.JLabel lblVolunteerPhno1;
    private javax.swing.JLabel lblVolunteerPhone;
    private javax.swing.JLabel lblVolunteerState;
    private javax.swing.JLabel lblVolunteerZip;
    private javax.swing.JLabel lblVolunteerage;
    private javax.swing.JLabel lblVolunteercopwd1;
    private javax.swing.JLabel lblVolunteerid;
    private javax.swing.JLabel lblVolunteerid2;
    private javax.swing.JLabel lblVolunteername;
    private javax.swing.JLabel lblVolunteername1;
    private javax.swing.JLabel lblVolunteerpwd;
    private javax.swing.JLabel lblVolunteerpwd2;
    private javax.swing.JLabel lblVolunteeruname;
    private javax.swing.JLabel lblVolunterZip1;
    private javax.swing.JTextField txtVolunteerAdd;
    private javax.swing.JTextField txtVolunteerCity;
    private javax.swing.JTextField txtVolunteerExp;
    private javax.swing.JTextField txtVolunteerPhone;
    private javax.swing.JTextField txtVolunteerState;
    private javax.swing.JTextField txtVolunteerZip;
    private javax.swing.JTextField txtVolunteerage;
    private javax.swing.JTextField txtVolunteercopwd1;
    private javax.swing.JTextField txtVolunteerid;
    private javax.swing.JTextField txtVolunteername;
    private javax.swing.JTextField txtVolunteerpwd;
    private javax.swing.JTextField txtVolunteeruname;
    // End of variables declaration//GEN-END:variables

    private boolean chkpwd() {
        if (txtVolunteerpwd.getText().equals(txtVolunteercopwd1.getText())) {
            return true;
        } else {
            return false;
        }
    }
}
