/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.NonGovtOrg.NonGovtOrg;
import Business.NonGovtOrgVolunteer.NGOVolunteerRequests;
import Business.NonGovtOrgVolunteer.NGOVolunteer;
import Business.FoodRequestorder.FoodRequestorder;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sowmyachinimilli
 */
public class RequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Requests
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String ngoAName;
    String nogName = "";

    public RequestsPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        ngoAName = userAcc.getEmployee().getName();
        for (NonGovtOrg ng : ecosystem.getNgoDir().getNgoList()) {
            if (ng.getNgoAgent().equals(ngoAName)) {
                nogName = ng.getNgoName();
            }
        }
        setBG();
        makeTableTransparent1();
        makeTableTransparent();
        populateRTable();
        populateVTable();
        //tblV.setVisible(false);
        // btnAvail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddReqFCTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblFCReq = new javax.swing.JTable();
        btnFCReqAvail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarehouse = new javax.swing.JTable();
        btnWHProcess = new javax.swing.JButton();
        lblAddWHTitle = new javax.swing.JLabel();
        lblWarehouse = new javax.swing.JLabel();
        lblRequestID = new javax.swing.JLabel();
        lblReq = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddReqFCTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblAddReqFCTitle.setForeground(new java.awt.Color(0, 153, 204));
        lblAddReqFCTitle.setText("Requests from Food Cloud");
        add(lblAddReqFCTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 6, -1, -1));

        tblFCReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblFCReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Request", "Warehouse", "Number of Persons", "Status"
            }
        ));
        tblFCReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblFCReqMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblFCReq);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 59, 696, 129));

        btnFCReqAvail.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnFCReqAvail.setText("Make Available");
        btnFCReqAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCReqAvailActionPerformed(evt);
            }
        });
        add(btnFCReqAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 463, -1, -1));

        tblWarehouse.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Volunteer ID", "Name", "Address", "City", "Zip", "Status"
            }
        ));
        tblWarehouse.setGridColor(new java.awt.Color(0, 0, 0));
        tblWarehouse.setOpaque(false);
        tblWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblWarehouseMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblWarehouse);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 292, 814, 153));

        btnWHProcess.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnWHProcess.setText("Process");
        btnWHProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWHProcessActionPerformed(evt);
            }
        });
        add(btnWHProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 206, -1, -1));

        lblAddWHTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblAddWHTitle.setText("For Warehouse:");
        add(lblAddWHTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, -1, -1));

        lblWarehouse.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 241, -1, -1));

        lblRequestID.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblRequestID.setText("Request ID:");
        add(lblRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, -1, -1));

        lblReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 235, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 850));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1350, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(ManageVolunteerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void makeTableTransparent() {
        tblFCReq.setOpaque(false);
        ((DefaultTableCellRenderer) tblFCReq.getDefaultRenderer(Object.class)).setOpaque(false);
        tblFCReq.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblFCReq.getModel().getColumnCount(); i++) {
            tblFCReq.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    public void makeTableTransparent1() {
        tblWarehouse.setOpaque(false);
        ((DefaultTableCellRenderer) tblWarehouse.getDefaultRenderer(Object.class)).setOpaque(false);
        tblWarehouse.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblWarehouse.getModel().getColumnCount(); i++) {
            tblWarehouse.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    

    private void btnFCReqAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCReqAvailActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblWarehouse.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblWarehouse.getModel();
        NGOVolunteer selectedV = (NGOVolunteer) model.getValueAt(selectedRowIndex, 0);
        if (selectedV.getVolAvail().equals("New") || selectedV.getVolAvail().equals("No")) {
            selectedV.setVolAvail("Yes");
            String reqidval = lblReq.getText();
            for (NGOVolunteerRequests vr : ecosystem.getVRDirectory().getVrList()) {
                if (vr.getVolreqId().equals(reqidval)) {
                    vr.setVolreqStatus("Completed");
                }
            }
            JOptionPane.showMessageDialog(this, "Request Completed");
        } else if (selectedV.getVolAvail().equals("Yes")) {
            JOptionPane.showMessageDialog(this, "This Volunteer is already available");
        }
        populateRTable();
        populateVTable();
        lblReq.setText("");
        lblWarehouse.setText("");
    }//GEN-LAST:event_btnFCReqAvailActionPerformed

    private void btnWHProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWHProcessActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFCReq.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblFCReq.getModel();
        NGOVolunteerRequests selectedVR = (NGOVolunteerRequests) model.getValueAt(selectedRowIndex, 0);
        if (selectedVR.getVolreqStatus().equals("Completed")) {
            JOptionPane.showMessageDialog(this, "Request already completed!");
        } else {
            lblWarehouse.setText(selectedVR.getVolreqWH());
            lblReq.setText(selectedVR.getVolreqId());
            tblWarehouse.setVisible(true);
            btnFCReqAvail.setVisible(true);
        }
        populateVTable();
    }//GEN-LAST:event_btnWHProcessActionPerformed

    private void tblFCReqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFCReqMousePressed
        // TODO add your handling code here:
                tblFCReq.setSelectionForeground(Color.BLACK);
    }//GEN-LAST:event_tblFCReqMousePressed

    private void tblWarehouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWarehouseMousePressed
        // TODO add your handling code here:
                tblWarehouse.setSelectionForeground(Color.BLACK);
    }//GEN-LAST:event_tblWarehouseMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnFCReqAvail;
    private javax.swing.JButton btnWHProcess;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddReqFCTitle;
    private javax.swing.JLabel lblAddWHTitle;
    private javax.swing.JLabel lblReq;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblWarehouse;
    private javax.swing.JTable tblFCReq;
    private javax.swing.JTable tblWarehouse;
    // End of variables declaration//GEN-END:variables

    private void populateRTable() {
        DefaultTableModel model = (DefaultTableModel) tblFCReq.getModel();
        model.setRowCount(0);
        for (NGOVolunteerRequests vr : ecosystem.getVRDirectory().getVrList()) {
            if (vr.getVolreqName().equals(nogName)) {
                Object[] row = new Object[6];
                row[0] = vr;
                row[1] = vr.getVolreqName();
                row[2] = vr.getVolreqWH();
                row[3] = vr.getVolreqNum();
                row[4] = vr.getVolreqStatus();
                model.addRow(row);
            }
        }
    }

    private void populateVTable() {
        DefaultTableModel model = (DefaultTableModel) tblWarehouse.getModel();
        model.setRowCount(0);
        for (NGOVolunteer vol : ecosystem.getVolDir().getVolunteerList()) {
            if (vol.getVolNGO().equals(ngoAName)) {
                Object[] row = new Object[6];
                row[0] = vol;
                row[1] = vol.getVolName();
                row[2] = vol.getVolAddress();
                row[3] = vol.getVolCity();
                row[4] = vol.getVolZipcode();
                row[5] = vol.getVolAvail();
                model.addRow(row);
            }
        }
    }
}
